### ISSUE TITLE
Nuki Opener

### ISSUE THREAD

**Issue by lukasroegner** [lukasroegner/homebridge-nuki#1]
I just received the Nuki Opener (still waiting for the Bridge), did not find an existing plugin for it. As the Nuki Lock 2.0 already has HomeKit support, this plugin will initially focus on the Opener.

I already tested some variants in the HomeKit Accessory Simulator in order to look nice in the iOS 13 Home app. Also went through the API docs for Nuki.

* The Opener will be implemented as an accessory with a lock mechanism (primary service) and a doorbell service
* Home app supports notification if the bell rings.
* The Nuki Bridge API (which I prefer) does not support ring notification, the Web API seems to support it via `/Notification`
* I'll start to implement it using the Web API, switch to the local Bridge API as soon as `/callback` supports all types of events
* Settings (changing RTO, suppressing bell) will be added later on as a separate accessory with switches for the services

**Comment by lukasroegner** [comment]
@CooperCGN Might also be interesting for you?

**Comment by CooperCGN** [comment]
Hehe, Opener already here but installation instructions unclear in the app, waiting for support to 
answer

**Comment by CooperCGN** [comment]
Got feedback from support but can’t get it to work which is weird as the nello worked without problems. If you don’t mind please leave some feedback here if you get it to work and how you run the cables.

**Comment by lukasroegner** [comment]
Which manufacturer/model is your intercom?

**Comment by CooperCGN** [comment]
It’s a bticino BT334704
http://www.elettrotechshop.it/public/334704-bticino-citofono-swing-bianco-334704-cornetta.php?c=2109

**Comment by CooperCGN** [comment]
I really don’t want to go back to the nello as the sleek looking integration of both doors in the Nuki app is awesome

**Comment by lukasroegner** [comment]
I‘m quite happy with the Nello, however, my plugin still has to use a relay server to translate webhooks to websocket connections. Will be the same issue with the Nuki for the initial implementation, but I guess they will implement advanced notification support for the WiFi bridge soon

**Comment by CooperCGN** [comment]
Just wanted to give some feedback on the opener, really curious what your experience will be. After a while trying I got it finally running. Now comes the big BUT! When away from home it takes the app forever to connect to my nuki lock and the opener, sometimes it will simply time out and say "not available" on both. Only force closing the app will work then. This takes so long, by the time I already found the key to open the door.

On top every time I arrive at home the app suddenly started to alarm me with an error, once it was that the nuki wasn't calibrated anymore (I haven't touched it and it works normal), the second time it told me that the opener had the wrong time in settings.

I wil reset the opener and the bridge during the weekend and will give it one more try, but I have a strong feeling that the nello is better because it connects directly to the wifi at home without a slow BT connection in between.

**Comment by lukasroegner** [comment]
Still waiting for the bridge, no answer from the Nuki support regarding arrival date...I use the Nuki Smart Lock via HomeKit (no Bridge) and it is a fantastical device (although consumes a lot of energy).

I have had issues with the nello from time to time (no WiFi connection), resetting the device is horrible (its 2019, no need to communicate via light patterns). I hope that the Nuki Opener works better in my environment.

**Comment by CooperCGN** [comment]
luckily my router supports having a separate SSID for 2,4GHz only stuff on the same network. But you're right, the light pattern thing is soooo 1980 :-)

**Comment by CooperCGN** [comment]
I use black eneloop batteries with my Nuki, need to charge them maybe every five to six months.

**Comment by lukasroegner** [comment]
My lock is rather hard to open (a lot of force is needed to turn the key), this is the reason why I have to replace batteries that open. I'll try the eneloop accumulators, thanks for the suggestion.

**Comment by CooperCGN** [comment]
Oh, by the way, maybe we need to switch to opener anyway:
https://www.digitalzimmer.de/artikel/news/betreiber-des-smarten-tueroeffners-nello-ist-insovent/

**Comment by lukasroegner** [comment]
Initial implementation completed. The plugin communicates the the Nuki Wifi Bridge, not with the Web API. Plugin supports SmartLock and Opener. I already filed a feature request for Nuki Bridge callbacks when the bell rings. As soon as the door sensor of the Nuki SmartLock is integrated into the Bridge, it will also be added.

**Comment by felixmueller** [comment]
> I already filed a feature request for Nuki Bridge callbacks when the bell rings. As soon as the door sensor of the Nuki SmartLock is integrated into the Bridge, it will also be added.

Is there any chance of getting the doorbell feature using the Web API before Nuki decides to update the Bridge API? That may take a long time and we don't know if it happens at all. I loved the feature to be notified if someone rings the bell when using nello one back in the days.
Thank you so much.

**Comment by lukasroegner** [comment]
Technically, there is nothing too difficult (but takes some time). The actual issue is that I have to provide a server that acts as a relay for the web hooks of the Nuki Web API (which is annoying and you end up relying on an internet connection for a device that is already on your local network). Moreover, the notifications of the Web API seem to have a delay of approx. 30 seconds, which is not satisfying if you want to get "real-time" notifications for bell rings.

I want to wait for at least a month and check if the guys at Nuki manage to get their Bridge development done properly. If not...I gonna implement the Web API communication.

Another idea would be to check whether the calls of the Bridge to the Web API could be intercepted, however, I haven't tried to do that, yet.
