### ISSUE TITLE
Question about the security of HomeKit unlatch functionality

### ISSUE THREAD

**Issue by felixmueller** [lukasroegner/homebridge-nuki#10]
Hi Lukas,

I got a Nuki Smart Lock yesterday and added it to HomeKit using the native HomeKit support of the lock.
Out of the box, the lock doesn't support the separation of unlock and unlatch, so that I find it quite dangerous to use the native HomeKit integration. If I accidentally hit the lock in the Home app, the door will open immediately and I have no way to close it while not at home.

So here is my question: If I remove the lock from HomeKit and re-add it using the homebridge-nuki plugin, the behavior will change to a much more secure one, if I set the configuration as follows:
```
unlatchFromLockedToUnlocked: false
unlatchFromUnlockedToUnlocked: true
```

If I then accidentally hit the lock in the Home app, the lock will just unlock and not unlatch. Unlatching will only take place if I swipe the unlocked lock to lock state and then back to unlock state without releasing my finger or if I ask Siri to open the door if it is already unlocked.

So, did I get this right and there is then no way to accidentally unlatch the door by tapping?

Thank you very much!

Cheers
Felix

**Comment by lukasroegner** [comment]
Hi Felix, yes, this is exactly why I implemented the additional settings.

**Comment by felixmueller** [comment]
Thanks a lot Lukas! I will try it out later today.

**Comment by felixmueller** [comment]
Hi Lukas,

I now removed my native HomeKit connection to the lock and added it again using your plugin.

The basics work, but the unlatch feature doesn't work as I expected it to work:
- Assumption: I have the `unlatchFromUnlockedToUnlocked` set to true and the lock state is unlocked
- When I swipe the lock state to locked and (without releasing my finger) back to locked, is the lock supposed to do a full lock, then unlock and then unlatch?
- Isn't it possible to do an unlatch immediately?
- How is the behavior when I enable the unlatchLock parameter, is the unlatch possible when the lock state is locked?

Additionally, from time to time, I get the following message:
`Error while communicating with the Nuki Bridge. Status Code: 503`

Thank you very much again for your support!

**Comment by felixmueller** [comment]
Hi Lukas,

here is a little update:

I now tried the `unlatchLock` instead of the `unlatchFromUnlockedToUnlocked` setting and it looks quite good unter iOS 13. Because the unlatch lock service is added as a second service to the lock accessory, there is no way to accidentally open the door anymore. It always needs 2 taps to reach the latch lock, and Siri always opens the lock itself when telling her to open the door unless I explicitly tell her to open the latch.

I like it very much how it works now!

There is only one suggestion: what do you think about adding a setting to prevent opening the latch when the lock is locked? It will then not be possible to accidentally open the door if the lock is closed and there will always be 2 steps needed via HomeKit: 1. open the lock, 2. open the latch.

What do you think about it?

Thank you very much!

Best regards,
Felix

**Comment by lukasroegner** [comment]
> Assumption: I have the unlatchFromUnlockedToUnlocked set to true and the lock state is unlocked
> When I swipe the lock state to locked and (without releasing my finger) back to unlocked, is the lock supposed to do a full lock, then unlock and then unlatch?
> Isn't it possible to do an unlatch immediately?

No, it should directly unlatch the door. You can also use Siri to check that (tell Siri to unlock the door when it is already unlocked).

**Comment by lukasroegner** [comment]
> There is only one suggestion: what do you think about adding a setting to prevent opening the latch when the lock is locked? It will then not be possible to accidentally open the door if the lock is closed and there will always be 2 steps needed via HomeKit: 1. open the lock, 2. open the latch.

An additional setting for the `unlatchLock` could be implemented, e.g. `unlatchLockPreventIfLocked`, so that nothing is done when you try to unlatch a locked door.

**Comment by felixmueller** [comment]
This topic is way more complex than I thought 😊

There are some good suggestions in [this post](https://developer.nuki.io/t/make-homekit-nuki-mapping-selectable-to-enable-users-to-trigger-the-unlock-command-to-the-nuki-smart-lock-2-0-instead-of-triggering-the-open-door-command/1682) of the Nuki Developer Forum.

A `virtualBolt` setting as mentioned in the post looks like an interesting solution to me, too.

**Comment by lukasroegner** [comment]
Indeed, it has always been an issue that HomeKit does not have an "unlatched" state, as deadbolts are common in the US. Personally, I don't think that (small to medium-sized) vendors will ever convince Apple to expand their `LockMechanism` API. That's why nearly all homebridge plugins that expose locks think of more secure solutions that prevent unintentional unlatching.

IMHO, adding an option to prevent unlatching when the door is locked is enough to prevent unintentional unlatching. Automations in HomeKit can always check the status of accessories and use them in conditions, which also prevents unintentional unlatching.

**Comment by felixmueller** [comment]
I will close the issue for now, I think the plugin configuration options are good enough for the current state of the lock and HomeKit capabilities.
Thanks a lot!

**Comment by lukasroegner** [comment]
@felixmueller Implemented the safety mechanism, that there is an option to disable the unlatch lock (second lock) operation if the Nuki is locked. You can set the new property `unlatchLockPreventUnlatchIfLocked` in the `config.json`. Latest version is on the `development` branch. If you have time, you can check it out.

**Comment by felixmueller** [comment]
@lukasroegner Thank you very much for adding this, I will check it out as soon I have some spare time.

Q: How will the unlatch lock behave in the Home app if the unlatch is blocked? Will it snap back to locked after moving it to unlocked instantly?

**Comment by lukasroegner** [comment]
It will snap back, disabling accessories is currently not supported in HomeKit.
