### ISSUE TITLE
Question: Android Bridge App

### ISSUE THREAD

**Issue by beatpaul** [lukasroegner/homebridge-nuki#11]
Hi!
Is the homebridge Plugin compatible with the Android Bridge App?

**Comment by lukasroegner** [comment]
Hi @beatpaul, can you try It out? I don't have an Android device to test it out.

**Comment by beatpaul** [comment]
Hi!
@lukasroegner I just have the nuki lock, not the (opener which i‘m interested in)

Maybe i find some time on the weekend

**Comment by lukasroegner** [comment]
@beatpaul there is a post from Nuki in the developer forum that states that they do not plan to integrate the opener into the Software Bridge anytime soon: https://developer.nuki.io/t/android-bridge-app-mit-nuki-opener/2661/2
