### ISSUE TITLE
Locks responding very slow or not at all

### ISSUE THREAD

**Issue by joey2212** [lukasroegner/homebridge-nuki#15]
Hey Lukas,

First of all: thank you so much for this plugin.

Everything shows up working in the home app and for the first 1 or 2 actions everything works fine. I have an Opener and a Smart Lock connected to the bridge. Problem is: After the first 1 or 2 actions the locks still show that they're responding, but nothing happens. After opening the nuki app and opening / closing locks, the home app updates - yet I can't start new actions from the home app because nothing happens. Log shows no errors, just gets stuck at: [10/8/2019, 5:34:29 PM] [NukiPlatform] XXXXXXXXX - Unlock

Help? :/

Best Regards,
Johannes

**Comment by lukasroegner** [comment]
Hi @joey2212,

Thank you for using the plugin! You describe the issue, that most people have when using the Nuki Bridge (see https://developer.nuki.io/t/random-http-503-unavailable/909). I tried to implement some features to overcome the issues of the Bridge, which includes

* Retry of requests that get the 503 response
* Serialization of requests (only one at a time is sent)
* "Recovery" time between each request to the Nuki Bridge, which means the plugin tries to wait some time between requests

As your log stuck at "Unlock" (and you did not get further errors in the log), I assume that the Bridge stopped to send callback notifications. I'm sorry that I cannot give proper advice other than wait for a firmware update of the Bridge (which we are all waiting for!).

Feel free to provide a more detailed log if it happens again, I'll take a look at it, maybe the plugin can be improved further.

**Comment by lukasroegner** [comment]
Hi @felixmueller,

Sounds strange, the request to reboot the Bridge is also queued on the request queue, which means that the previous requests (3 time "open" request) had to be completed (or each one failed 3 times in a row) before the reboot request dequeued and executed.

What do you think? Does the Bridge have some kind of queueing mechanism built in?
