### ISSUE TITLE
Batteriestatus wird falsch ausgelesen

### ISSUE THREAD

**Issue by MikeDeltaHH** [lukasroegner/homebridge-nuki#16]
Moin!
Bei mir wird im HB Plugin die Batterie als 100% voll geladen angezeigt während mir das Nuki selbst eben die Mitteilung angezeigt hat dass die Batterien fast leer sind! Was brauchst Du alles an Infos oder ist das vielleicht eine Fuktion die noch nicht sauber läuft?

Gruß!
Michael

**Comment by lukasroegner** [comment]
Hi Michael,

Can you perform an action via the Home app (e.g. unlock) and check whether the battery state updated in HomeKit? Maybe the callback from the Bridge signalling critical battery state has not been sent properly.

Another option would be to make calls to the Nuki Bridge in a fixed interval (e.g. once per hour) to update the general state of the locks.

**Comment by MikeDeltaHH** [comment]
Hi Lukas!
I think it was an error of the Nuki... the critical battery status is gone without any action this morning... strange!
