### ISSUE TITLE
Multiple Hubs?

### ISSUE THREAD

**Issue by redeemer666** [lukasroegner/homebridge-nuki#17]
Hello Lukas,

does your plugin support multiple nuki hubs? I have two of them and am interested to know if I can use your plugin on both or I have to start a second homebridge instance like others plugin. Thank you

**Comment by lukasroegner** [comment]
Hi @redeemer666,

I have not tested it out, but I think you can insert the 

```
{
  platform: 'NukiPlatform',
 ...
}
```

multiple times into the `platforms` array in the config.

**Comment by redeemer666** [comment]
Will give it a try, thank you for your fast answer!

**Comment by Speedy963** [comment]
if inserted twice, it's not working

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 91......

**Comment by lukasroegner** [comment]
@Speedy963 Did you add two different bridges to the config?

**Comment by Speedy963** [comment]
Hi,

 

danke für die Rückmeldung.

 

 

Ich habe das einfach wie folgt eingetragen. 

2 Bridges mit unterschiedlicher IP, die nukiId und Token sind natürlich anders:

 

 

       {

            "platform": "NukiPlatform",

            "hostNameOrIpAddress": "hoobs.local",

            "hostCallbackApiPort": 40506,

            "bridgeIpAddress": "192.168.110.95",

            "bridgeApiPort": 8080,

            "bridgeApiToken": "xxxxx",

            "bridgeRebootSwitch": false,

            "devices": [

                {

                    "nukiId": 111111111,

                    "isRingToOpenEnabled": false,

                    "isContinuousModeEnabled": false,

                    "unlatchFromLockedToUnlocked": false,

                    "unlatchFromUnlockedToUnlocked": false,

                    "unlatchLock": false

                }

            ]

        },

        {

            "platform": "NukiPlatform",

            "hostNameOrIpAddress": "hoobs.local",

            "hostCallbackApiPort": 40506,

            "bridgeIpAddress": "192.168.110.28",

            "bridgeApiPort": 8080,

            "bridgeApiToken": "xxxxx",

            "bridgeRebootSwitch": false,

            "devices": [

                {

                    "nukiId": 2222222222,

                    "isRingToOpenEnabled": false,

                    "isContinuousModeEnabled": false,

                    "unlatchFromLockedToUnlocked": false,

                    "unlatchFromUnlockedToUnlocked": false,

                    "unlatchLock": false

                }

            ]

        }

 

 

 

Viele Grüße

Jürgen

 

Von: Lukas Rögner <notifications@github.com>
Antworten an: lukasroegner/homebridge-nuki <reply@reply.github.com>
Datum: Mittwoch, 20. November 2019 um 10:31
An: lukasroegner/homebridge-nuki <homebridge-nuki@noreply.github.com>
Cc: Jürgen Müller <juergen-mueller@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [lukasroegner/homebridge-nuki] Multiple Hubs? (#17)

 

@Speedy963 Did you add two different bridges to the config?

**Comment by redeemer666** [comment]
Hello Speedy and thank for stepping in. Just after I asked it my second bridge died so I was not able to check it. If you try to change the callback and API ports do you have any luck?

**Comment by lukasroegner** [comment]
@Speedy963 It seems that using multiple instances of the same plugin does not work properly (see https://github.com/nfarina/homebridge/issues/1736) as there is no mechanism that creates a unique plugin "ID", just the plugin name to identify it.

What you should do in any case: Change the `hostCallbackApiPort` of the second entry (to a random number, e.g. +1). This is the port on your homebridge device (e.g. Raspberry Pi) that is used to receive callbacks. A port can only be used by a single service.

Possible workarounds:
* Start multiple homebridge instances with multiple config.json files
* Fork the plugin, do a search-and-replace on `NukiPlatform` to `NukiPlatformTwo`, commit the change and install the second plugin from the git URL of the fork. Now you can use the platforms `NukiPlatform` (from NPM) and `NukiPlatformTwo` from your fork's git URL
