### ISSUE TITLE
Second lock no longer switches

### ISSUE THREAD

**Issue by Nastras** [lukasroegner/homebridge-nuki#19]
Hello lukas,

i guess since the last firmware update of Nuki for the locks i don't use your plugin to control both locks in automations anymore.

It shows in the log the and homekit the status change but only executes it for one lock actually.

If I switch the locks manually into homekit it works.

So far everything had worked great. Do you have any idea where the problem is?

**Comment by Nastras** [comment]
I have now tested a bit more and could see in the log that it is again a callback problem from the bridge.

So far your plugin processed the calbacks if they were faulty very well that both locks worked.


Now if I use both locks at the same time one lock will be closed and the second one will change in homekit the status but nothing happens.

I restarted the bridge several times to test it.

Which surprises me, that it has worked without problems for a long time now.

![40D129A8-EB13-4EAA-B2DD-48DE43C05DC7](https://user-images.githubusercontent.com/27686185/69071094-9cdeb780-0a29-11ea-8da7-ccd61e7c166a.jpeg)

**Comment by Nastras** [comment]
![5687EC37-508B-4E6C-BE94-B80578BB0FC5](https://user-images.githubusercontent.com/27686185/69071144-b8e25900-0a29-11ea-97a6-83129f16a499.jpeg)

**Comment by lukasroegner** [comment]
@Nastras If it worked for you for a while, it must be the firmware update. I'm still waiting for public release of the big firmware update that contains the rewritten HTTP endpoint. This might solve all of the 503 issues.

**Comment by Nastras** [comment]
That's what I think. For the time being I helped myself to integrate the second Nuki natively.

Where did you get the info that a new big firmware is soon available for the bridge? Of course that would be great if nuki fixes that.

I already thought about buying a second one.

**Comment by lukasroegner** [comment]
@Nastras See https://developer.nuki.io/t/random-http-503-unavailable

**Comment by Nastras** [comment]
Cool, I wasn't aware that Nuki was working on an update for the bridge.

The way it looks, it's already released.

![65A02E20-5EDB-4CDE-AE4A-83D371487758](https://user-images.githubusercontent.com/27686185/69335960-0c3ced00-0c5e-11ea-8a60-9b966d89d7b8.jpeg)


Unfortunately the Nuki App doesn't offer an update yet 😒
Do you know if it can be started manually?

I'm curious.

**Comment by felixmueller** [comment]
Hi @lukasroegner,

did you already manage to perform some tests with plugin using the new firmware version?
https://developer.nuki.io/t/nuki-bridge-firmware-release-notes-public-releases/2797

I hope that they will now start developing new features to the Bridge API, like a callback notification when the bell rings.

Cheers
Felix

**Comment by Nastras** [comment]
Good morning @lukasroegner ,

I have now updated the firmware 2.4.8 for the Bridge and nukis 2.6.4. Unfortunately it still doesn't work.

I created for a test two scenes in HomeKit where both switch nukis.

Scene 1 both nuki = unlocked
Scene 2 both nukis = lock

I have tested it several times it is always controlled only one Nuki the second does not react.

So there seems to be a need for action on the plugin?

Thanks you for your effort!


Nov 22 08:18:25 HBS homebridge[30758]: [NukiPlatform] Callback received.
Nov 22 08:18:25 HBS homebridge[30758]: [NukiPlatform] XXXX97181 - Updating lock state: SECURED/SECURED
Nov 22 08:18:25 HBS homebridge[30758]: [NukiPlatform] XXXX97181 - Updating critical battery: false
Nov 22 08:19:18 HBS homebridge[30758]: [NukiPlatform] XXXX07085 - Lock
Nov 22 08:19:18 HBS homebridge[30758]: [NukiPlatform] XXXX97181 - Unlock
Nov 22 08:19:34 HBS homebridge[30758]: [NukiPlatform] Callback received.
Nov 22 08:19:34 HBS homebridge[30758]: [NukiPlatform] XXXX07085 - Updating lock state: SECURED/SECURED
Nov 22 08:19:34 HBS homebridge[30758]: [NukiPlatform] XXXX07085 - Updating critical battery: false
Nov 22 08:19:41 HBS homebridge[30758]: [NukiPlatform] Callback received.
Nov 22 08:19:41 HBS homebridge[30758]: [NukiPlatform] XXXX97181 - Updating lock state: UNSECURED/UNSECURED
Nov 22 08:19:41 HBS homebridge[30758]: [NukiPlatform] XXXX97181 - Updating critical battery: false

**Comment by lukasroegner** [comment]
@Nastras Haven't had time to install the new firmware. There are several things that can be enhanced if the new firmware works as expected:

* There is a "sleep" time for the plugin between sending requests (the requests are queued, they are not lost) which can be decreased or removed
* There is a queue for requests which could be removed

Anyways, I noticed that there are two actions within the same second (which may be the trigger of the scene):
```
Nov 22 08:19:18 HBS homebridge[30758]: [NukiPlatform] XXXX07085 - Lock
Nov 22 08:19:18 HBS homebridge[30758]: [NukiPlatform] XXXX97181 - Unlock
```

It says the first lock gets locked, the second one unlocked. That is not how you described the scene.

**Comment by Nastras** [comment]
Hey, lucas, thanks for the quick answer.
I just checked the scenes again and it looks like you're right. It seems to be a display bug in the HomeKit app I use or icloud bug. I have recreated the trigger in another app and now it works perfectly again. Sometimes you can't see the forest for the trees anymore -.- 

What surprises me is that it worked for a long time before and suddenly doesn't work anymore. HomeKit just works 🤪

You can lean back, it seems as if it was a false alarm from me. Sorry for the circumstances.

And thanks for the help 👌
