### ISSUE TITLE
homebridge start fails after install this pulgin

### ISSUE THREAD

**Issue by testpaul999** [lukasroegner/homebridge-nuki#2]
if i install this plugin my homebridge won't start.
this is my log 

Sep 16 09:43:39 386pi homebridge[30569]: [2019-9-16 09:43:39] TypeError: Cannot read property 'indexOf' of undefined
Sep 16 09:43:39 386pi homebridge[30569]:     at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:120:12)
Sep 16 09:43:39 386pi homebridge[30569]:     at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
Sep 16 09:43:39 386pi homebridge[30569]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
Sep 16 09:43:39 386pi homebridge[30569]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Sep 16 09:43:39 386pi homebridge[30569]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Sep 16 09:43:39 386pi homebridge[30569]:     at Module._compile (module.js:653:30)
Sep 16 09:43:39 386pi homebridge[30569]:     at Object.Module._extensions..js (module.js:664:10)
Sep 16 09:43:39 386pi homebridge[30569]:     at Module.load (module.js:566:32)
Sep 16 09:43:39 386pi homebridge[30569]:     at tryModuleLoad (module.js:506:12)
Sep 16 09:43:39 386pi homebridge[30569]:     at Function.Module._load (module.js:498:3)
Sep 16 09:43:39 386pi homebridge[30569]:     at Function.Module.runMain (module.js:694:10)
Sep 16 09:43:39 386pi homebridge[30569]:     at startup (bootstrap_node.js:204:16)
Sep 16 09:43:39 386pi homebridge[30569]:     at bootstrap_node.js:625:3
Sep 16 09:43:39 386pi homebridge[30569]: Uncaught exception error:  TypeError: Cannot read property 'indexOf' of undefined
Sep 16 09:43:39 386pi homebridge[30569]:     at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:120:12)
Sep 16 09:43:39 386pi homebridge[30569]:     at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
Sep 16 09:43:39 386pi homebridge[30569]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
Sep 16 09:43:39 386pi homebridge[30569]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Sep 16 09:43:39 386pi homebridge[30569]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Sep 16 09:43:39 386pi homebridge[30569]:     at Module._compile (module.js:653:30)
Sep 16 09:43:39 386pi homebridge[30569]:     at Object.Module._extensions..js (module.js:664:10)
Sep 16 09:43:39 386pi homebridge[30569]:     at Module.load (module.js:566:32)
Sep 16 09:43:39 386pi homebridge[30569]:     at tryModuleLoad (module.js:506:12)
Sep 16 09:43:39 386pi homebridge[30569]:     at Function.Module._load (module.js:498:3)
Sep 16 09:43:39 386pi homebridge[30569]:     at Function.Module.runMain (module.js:694:10)
Sep 16 09:43:39 386pi homebridge[30569]:     at startup (bootstrap_node.js:204:16)
Sep 16 09:43:39 386pi homebridge[30569]:     at bootstrap_node.js:625:3
Sep 16 09:43:40 386pi homebridge[30569]: (node:30569) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
Sep 16 09:43:40 386pi homebridge[30569]: [2019-9-16 09:43:40] Got SIGTERM, shutting down Homebridge...

need any help.

regards

**Comment by testpaul999** [comment]
this is my config part

{
            "platforms": [
                {
                    "platform": "NukiPlatform",
                    "hostNameOrIpAddress": "386pi.fritz.box",
                    "hostCallbackApiPort": 40506,
                    "bridgeIpAddress": "192.168.2.246",
                    "bridgeApiPort": 8089,
                    "bridgeApiToken": "miniD6",
                    "devices": [
                        {
                            "nukiId": 0,
                            "isRingToOpenEnabled": false,
                            "isContinuousModeEnabled": false,
                            "unlatchFromLockedToUnlocked": false,
                            "unlatchFromUnlockedToUnlocked": false,
                            "unlatchLock": false
                        }
                    ]
                }
            ]
        }

**Comment by lukasroegner** [comment]
@testpaul999 It seems that homebridge is not able to load a platform from the configuration (does not find the type of the platform). Can you tell me the version of homebridge, node your are using?

Did you use your homebridge instance before or is this the first time you are using homebridge? Does this happen with other plugins (https://www.npmjs.com/package/homebridge-dummy is a good plugin for checking that)?

**Comment by testpaul999** [comment]
node version 8.16.1
have running many plugins, like max!platform, Fritz!, configUI
all running fine if i uninstall your plugin

**Comment by lukasroegner** [comment]
Can you check if you have an empty object (i.e. an object without the "platform" property) in the array of platforms? The error means that the configuration is read, and for one item in the "platforms" array, the "platform" property cannot be read.

**Comment by testpaul999** [comment]
the config is fine, the config_ui check this if it save the changes

**Comment by testpaul999** [comment]
Auf dem neuesten Stand
Version 0.4.50
version homebridge

**Comment by lukasroegner** [comment]
Ok, so node and homebridge versions should clearly not be the issue.

**Comment by testpaul999** [comment]
that's i get if i install manually

pi@386pi:/usr/lib/node_modules$ sudo npm install homebridge-nuki --unsafe-perm
npm WARN saveError ENOENT: no such file or directory, open '/usr/lib/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/usr/lib/package.json'
npm WARN lib No description
npm WARN lib No repository field.
npm WARN lib No README data
npm WARN lib No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ homebridge-nuki@0.3.0
added 1 package, removed 1 package and audited 13169 packages in 22.287s
found 18 vulnerabilities (2 low, 2 moderate, 14 high)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@386pi:/usr/lib/node_modules$

**Comment by lukasroegner** [comment]
Is this the way you install your node modules manually? Usually, you would use `npm install -g <name-of-plugin>` to install a package globally.

However, it seems that the plugin has been installed?

**Comment by testpaul999** [comment]
no same issue at start homebridge

**Comment by lukasroegner** [comment]
See https://github.com/nfarina/homebridge/issues/2080

It seems the issue is related to the layout of your `config.json`. Make sure that there is only one `platforms` array and that all items in the `platforms` array have the `platform` property.

**Comment by testpaul999** [comment]
you are right! thx i have two platforms, my issue
