### ISSUE TITLE
Nuki Bridge new firmware version 2.4.10

### ISSUE THREAD

**Issue by felixmueller** [lukasroegner/homebridge-nuki#20]
Hi @lukasroegner,

did you already manage to perform some tests with your plugin using the new firmware version? My bridge didn’t install the upgrade yet.
https://developer.nuki.io/t/nuki-bridge-firmware-release-notes-public-releases/2797

I hope this is not a common issue: https://developer.nuki.io/t/bridge-2-4-10-no-callbacks-anymore/3723/2

Thank you so much!

Cheers
Felix

P.S.: I hope that Nuki will now start developing new features to the Bridge API, like a callback notification when the bell rings.

**Comment by lukasroegner** [comment]
Hi @felixmueller,

I didn't have time yet to update the firmware...also, I want to wait a bit and see if the callback issue is a common one.

I'm going to refactor two of my homebridge plugins next weekend, maybe I'll check the firmware then.

**Comment by felixmueller** [comment]
Hi @lukasroegner,

it seems that Nuki pulled the Version 2.4.10 this morning. I really hope that my bridge didn't perform the upgrade yet. There is another post reporting that the upgrade broke the callback function.

I am confused now, because the release notes say that version 2.4.8 was released on 20.11.2019.

Do you know when the last version was released?

**Comment by lukasroegner** [comment]
Seems that they messed up the latest firmware updates a bit: https://developer.nuki.io/t/nuki-2-0-firmware-2-6-4-installed-although-not-even-released/3752

**Comment by felixmueller** [comment]
> Seems that they messed up the latest firmware updates a bit: https://developer.nuki.io/t/nuki-2-0-firmware-2-6-4-installed-although-not-even-released/3752

I think you are talking about the Smart Lock Firmware 2.6.4. I installed it on Friday and I had no issues so far.

The update I was talking about is the Bridge Firmware 2.4.8 / 2.4.10.

**Comment by lukasroegner** [comment]
I tested the new firmware for the last few days...works like a charm! @felixmueller I'm currently experimenting with HomeKit shortcuts (specifically lock the Nuki if the last person leaves the home without security question from HomeKit), seems to work quite well.
