### ISSUE TITLE
Feature Request: Additional cmd switch at the lock

### ISSUE THREAD

**Issue by Nastras** [lukasroegner/homebridge-nuki#22]
Hello Lukas, happy new year.

I have a favor to ask you in the hope that you make it possible in your plugin for me.

I am about to connect my [Gira BUS doorbell](https://forum.smartapfel.de/forum/thread/1857-mit-kontaktsensor-smarten-türgong-selbst-basteln/?postID=74729#post74729) to the Nuki opener. Gira is not officially supported by Nuki because the BUS signal is encrypted.

The following functions I can currently operate:

- Open
- Receiving the ring signal

Unfortunately I have no possibility to interrupt my ring signal via the opener to set the bell to silent because I am missing the ring cable.

I intend to use a relay directly at the doorbell station to silence the ring.

So I wanted to ask you if you can add an option to have an additional switch directly on the lock of the opener or nuki in homekit via the config.json which can send a CMD command.

Would be really great and would help me a lot.

Greeting Nastras

**Comment by lukasroegner** [comment]
Hi Nastras,

Can you set it all up with another plugin (`homebridge-cmd`) and make sure it works as expected? Then, I would fork the Nuki plugin for you and add the switch directly to the Opener.

Best regards
Lukas

**Comment by Nastras** [comment]
The implementation of my project with the opener is still in progress. It's taking longer than expected.

I would like to get back to you about this topic at the end of next week. I hope that is ok?

Thanks for the offered support. Really great 👌👍👌

**Comment by Nastras** [comment]
Hi Lukas, thanks again for your offer to create a fork especially for me.

I have found another solution for my problem. Therefore you do not need to do the work.
