### ISSUE TITLE
Display option for "isRingToOpenEnabled" and "IsContinuousModeEnabled"

### ISSUE THREAD

**Issue by Nastras** [lukasroegner/homebridge-nuki#23]
Hello Lukas, there is a possibility that you can install an option for the switches:

 "isRingToOpenEnabled"
 "isContinuousModeEnabled"

that these are displayed directly at the lock of the opener in homekit as switch and not as additional switches?

King Regards
Nastra

**Comment by Nastras** [comment]
Just like the unlatch variant 😉

![CC3B275E-5070-479E-BBC4-AB924D4B6D23](https://user-images.githubusercontent.com/27686185/71707401-ee7caf00-2de9-11ea-89b7-cb5a17626a66.jpeg)

**Comment by lukasroegner** [comment]
There has been a lengthly discussion about where to put settings switches in the Dyson plugin (see https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/6). I decided to put the switches in a separate accessory as they destroyed the layout of the main accessory.

That will also be the case with the lock accessory. If only one switch is enabled, it will flow below the two lock switches, which might look weird. What do you think?

**Comment by Nastras** [comment]
Ah ok, I haven't noticed that the home app shows the buttons when there are more than two because I usually use third party apps.

But can you add an option that lets the user decide in the config whether to bundle the switches in one device or create a separate switch for each function?

This would solve the problem because everybody can decide how he wants to have it?

In the homebridge-fritz-plugin of @Seydex I have already seen such a function.

**Comment by Nastras** [comment]
What do you think of the proposal?

**Comment by lukasroegner** [comment]
Sounds legit, I'll implement it when I have the time to.

**Comment by lukasroegner** [comment]
Please test out the `development` branch, I added a new configuration value `isSingleAccessoryModeEnabled`, which - when set to true - results in a single accessory for the Nuki Opener services.

**Comment by Nastras** [comment]
Hey Lukas, cool that you made it happen. Thanks👍

I've tried it and it all works like it should.

I think it doesn't look so bad in the home app. Didn't know that there are round switches now or is it a bug 😄?

![8F90FDAA-E57D-401B-96A7-457BACFD7E13](https://user-images.githubusercontent.com/27686185/72428869-e2500480-378e-11ea-98e4-12a9c494200f.jpeg)
![66D97573-8184-4242-911F-040A695CA493](https://user-images.githubusercontent.com/27686185/72428870-e2500480-378e-11ea-940b-628f8f017c64.jpeg)

And this is how it looks in HomeDash.
![A78975BA-84B0-4F2B-821C-FC707E7B7B5D](https://user-images.githubusercontent.com/27686185/72428915-014e9680-378f-11ea-8662-08b0e0b75978.jpeg)

**Comment by lukasroegner** [comment]
May be a bug or a feature, who knows ;)
I assume that Apple thought of using a lock and a single switch together, which might result in a vertical layout with the lock as button at the top and the switch centered below.

**Comment by lukasroegner** [comment]
I'll merge the changes into master as soon as #24 is tested.

**Comment by Nastras** [comment]
Who knows who knows 😂

The interesting thing about the thing is that the round button only pushes. It does not know any on or off in the home app.

I haven't seen it like this before because it's a function that is missing in homekit.

**Comment by lukasroegner** [comment]
No, I think that is the case because it is implemented that way: the open just opens, cannot be closed. When the Home app shows it as sliding switch and you slide-to-open it, it will immediately slide down.
