### ISSUE TITLE
[Feature Request] Support for Door Sensor of SmartLock 2.0

### ISSUE THREAD

**Issue by testpaul999** [lukasroegner/homebridge-nuki#25]
Hello,
I have nuki SmartLock 2.0 with Sensor and can't see the right state of the door.
Is it possible to get the state of the Doorsensor and bring this to Homebridge?

Thanks for try.

**Comment by lukasroegner** [comment]
Hi @testpaul999,

I'm waiting for the implementation by Nuki: https://developer.nuki.io/t/create-callback-for-door-sensor-status-in-bridge-api/1360
As soon as they update the Bridge API, contact sensor and bell ring will be implemented.

**Comment by testpaul999** [comment]
Thx, I’m happy with this answer. Hopefully they will bring this soon 😉

Liebe Grüße

Jens-Uwe

Am 17.01.2020 um 09:08 schrieb Lukas Rögner <notifications@github.com>:

﻿

Hi @testpaul999<https://github.com/testpaul999>,

I'm waiting for the implementation by Nuki: https://developer.nuki.io/t/create-callback-for-door-sensor-status-in-bridge-api/1360
As soon as they update the Bridge API, contact sensor and bell ring will be implemented.

**Comment by testpaul999** [comment]
Hi, now we get the possibility tonnage alarm if door open longer 2 min. 
Will you bring this in your plugin? Regards

**Comment by lukasroegner** [comment]
@testpaul999 I just checked the developer forum at Nuki, no new features for the Bridge API announced or released.

**Comment by testpaul999** [comment]
Oh, bad but thx for your response.

Liebe Grüße

Jens-Uwe

Am 15.05.2020 um 09:32 schrieb Lukas Rögner <notifications@github.com>:

﻿

@testpaul999<https://github.com/testpaul999> I just checked the developer forum at Nuki, no new features for the Bridge API announced or released.

**Comment by redeemer666** [comment]
Looks like they have enabled this function on the latest beta 😊

**Comment by testpaul999** [comment]
Cool, in welcher?

Liebe Grüße

Jens-Uwe

Am 17.06.2020 um 11:27 schrieb Andrea T. <notifications@github.com>:

﻿

Looks like they have enabled this function on the latest beta 😊

**Comment by testpaul999** [comment]
Hilft es zum Testen wenn ich mich auch für die Beta bei Nuki anmelde.

Liebe Grüße

Jens-Uwe

Am 17.06.2020 um 11:27 schrieb Andrea T. <notifications@github.com>:

﻿

Looks like they have enabled this function on the latest beta 😊

**Comment by lukasroegner** [comment]
I'll implement the sensor as soon as the firmware is out of beta!

**Comment by testpaul999** [comment]
Regards

Grüße

Jens-Uwe

Am 18.06.2020 um 09:32 schrieb Lukas Rögner <notifications@github.com>:

﻿

I'll implement the sensor as soon as the firmware is out of beta!

**Comment by felixmueller** [comment]
New Bridge API documentation v. 1.11: https://developer.nuki.io/t/new-bridge-api-documentation-v-1-11/6498

**Comment by lukasroegner** [comment]
Support for door sensor implemented in version 0.8.0. You can enable the door sensor with the option `isDoorSensorEnabled`. By default, the door sensor is exposed as a separate contact sensor. When setting `isSingleAccessoryModeEnabled` to `true`, the door sensor is added to the lock accessory (looks nice in the Apple Home app).

**Comment by felixmueller** [comment]
@lukasroegner Thank you you much for implementing this feature. It looks and works very well so far! Keep up the good work on this plugin!
![doorSensor](https://user-images.githubusercontent.com/115331/87447481-f0c29000-c5fa-11ea-9a1f-587f992bf9fb.png)

**Comment by testpaul999** [comment]
Thanks, it works very well 😁

Grüße

Jens-Uwe

Am 14.07.2020 um 17:54 schrieb Felix Mueller <notifications@github.com>:

﻿

@lukasroegner<https://github.com/lukasroegner> Thank you you much for implementing this feature. It looks and works very well so far! Keep up the good work on this plugin!
[doorSensor]<https://user-images.githubusercontent.com/115331/87447481-f0c29000-c5fa-11ea-9a1f-587f992bf9fb.png>
