### ISSUE TITLE
unlatsch on smart look no function

### ISSUE THREAD

**Issue by cosmit** [lukasroegner/homebridge-nuki#27]
i testet the Homebridge Nuki with the following config
"nukiId": xxxxxxxx 
                    "isRingToOpenEnabled": false,
                    "isContinuousModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "unlatchFromLockedToUnlocked": false,
                    "unlatchFromUnlockedToUnlocked": false,
                    "lockFromLockedToLocked": false,
                    "unlatchLock": true,
                    "unlatchLockPreventUnlatchIfLocked": true

i have the 2 switches in the HOME app; look and unlock is working perfect but the unlatch switch has no function; with unlock or looked.
<img width="380" alt="Bildschirmfoto 2020-01-20 um 13 34 14" src="https://user-images.githubusercontent.com/15158179/72726790-9388dd00-3b89-11ea-93d0-76c016db6608.png">

if i set unlock to unlock to true i also can produce a unlatch command on the log but not wies the Latch switch 

do you have any idea ?

**Comment by lukasroegner** [comment]
Fixed in #28, new version 0.7.4 on NPM.

Thank you for reporting the issue.
