### ISSUE TITLE
Expose doorbell as Sensor

### ISSUE THREAD

**Issue by Endlessknight** [lukasroegner/homebridge-nuki#29]
It should be possible to implement the doorbell of the Opener and show it as a Sensor so various shortcuts should be possible to make like light flashes, self made rings etc. if someone rings your door?

**Comment by lukasroegner** [comment]
Still waiting for Nuki to implement it: https://developer.nuki.io/t/nuki-bridge-api-bell-ring-of-nuki-opener-as-trigger-for-callbacks/2557, feel free to vote for the feature!

**Comment by 0ff** [comment]
@lukasroegner the request is now marked as "planned" by nuki and actually this function is available in the latest bridge firmware - would you accept a PR with the relevant changes?

**Comment by lukasroegner** [comment]
@0ff Feature is now implemented!
