### ISSUE TITLE
Enable/disable sound.

### ISSUE THREAD

**Issue by carlsendk** [lukasroegner/homebridge-nuki#30]
Ring to open with sound
Ring to open without sound

Another option is a switch with enable disable sound if possible.

I don't know what is best. My use case is when I'm the one opening the door there should be no sound so it's like me opening with a key. But if I'm expecting guest I would like to hear the sound.

**Comment by lukasroegner** [comment]
Same as with #31. As soon as the Bridge API supports it, I'll implement it.

**Comment by carlsendk** [comment]
Cool :-)
