### ISSUE TITLE
Plugin can only connect to NUKI bridge after restarting Homebridge

### ISSUE THREAD

**Issue by marcandre83** [lukasroegner/homebridge-nuki#32]
Whenever I reboot my pi, the plugin doesn't work and I get the following Error repeatedly:

[4/19/2020, 04:27:52] [NukiPlatform] Error while communicating with the Nuki Bridge. Error: Error: connect ENETUNREACH 192.168.1.26:8080 - Local (0.0.0.0:0)

As soon as I restart homebridge the nuki plugin starts working. Is there any way to prevent this?

**Comment by lukasroegner** [comment]
Hi @marcandre83,
It seems that the network connection is not initialized when homebridge is started. How do you start homebridge? If you use `systemd`, you might want to look into the service file:

Add `After=network-online.target` to the `[Unit]` section.

**Comment by marcandre83** [comment]
Hi @lukasroegner 
unfortunately this is not the problem, this is my homebridge.service:

[Unit]
Description=Homebridge
After=syslog.target network-online.target

any idea what else can be causing it?

**Comment by lukasroegner** [comment]
`ENETUNREACH` means Network unreachable. Maybe you should add some delay before homebridge is started, e.g.

```
[Service]
ExecStartPre=/bin/sleep 30
```

**Comment by marcandre83** [comment]
Thank you very much, that worked! I had the same problem on another Pi in another location, both are fresh installs of homebridge and nothing else, so I really wonder what other services hb needs to run correctly. But nevermind, this obviously is not the plugin's fault and again thank you very much!
