### ISSUE TITLE
Informations about homebridge 1.0.1

### ISSUE THREAD

**Issue by redeemer666** [lukasroegner/homebridge-nuki#33]
This is not a bug report, just a quick information to check whether this plugin is compatible with the latest version of homebridge (released today, 1.0.1) or not.

I really don’t want to disrupt my setup by update it, and since this plugin haven’t received many updates from a long time, want to check if it still works.

Thanks for the support

**Comment by beatpaul** [comment]
I‘m sorry to say that this is one of the plugins that doesnt work for me any more with homebridge 1.01 :( 
(at least with my settings rununning multiple instances on mac)
@lukasroegner thx for your plugin anyways :) , any suggestion on fixing it?

**Comment by redeemer666** [comment]
I also have two instances running, since I have 2 bridges. Hope @lukasroegner to update it to make it compatible with the latest update

**Comment by beatpaul** [comment]
I noticed that another plugin was causing the problem in the sane instsnce as nuki (homebridge-harmony) I had to clear the cache, but now everything Works flowless!!
Probably the nuki plugin works just fine without any trouble when updating :)

**Comment by lukasroegner** [comment]
@beatpaul Thank you for testing it out. @redeemer666 That should answer you question.
