### ISSUE TITLE
unlatchLock Status

### ISSUE THREAD

**Issue by Sheldor81** [lukasroegner/homebridge-nuki#35]
Hallo,

wenn ich "unlatchLock" aktiviere und die Tür dann mit dem neuen "Latch-Schalter" öffne bleibt der Schalter auf offen stehen. Um die Funktion dann noch einmal zu nutzen muss der Schalter dann erst auf geschlossen gestellt werden um die Tür dann wieder öffnen zu können.

**Comment by lukasroegner** [comment]
Hi @Sheldor81,
It seems that the bridge does not properly send requests to the registered callback URL. You can check that by
a) checking the logs: use the unlatch accessory in the Home app to unlatch the lock. After a few seconds, the bridge should send a request to the plugin to update the lock state back to "unlocked" instead of "unlatched".
b) checking the behavior: does HomeKit update the lock state properly if you execute an action (e.g. lock the door) via Nuki app?

**Comment by Sheldor81** [comment]
Hallo,

der Status wird nicht aktualisiert. Erst wenn die Homebridge neugestartet wird aktualisiert sich der Status.


`{
    "platform": "NukiPlatform",
    "hostNameOrIpAddress": "192.168.1.250",
    "hostCallbackApiPort": 40506,
    "bridgeIpAddress": "192.168.1.165",
    "bridgeApiPort": 8080,
    "bridgeApiToken": "XXX",
    "bridgeRebootSwitch": false,
    "devices": [
        {
            "nukiId": XXXXXX,
            "isRingToOpenEnabled": false,
            "isContinuousModeEnabled": false,
            "isSingleAccessoryModeEnabled": false,
            "unlatchFromLockedToUnlocked": false,
            "unlatchFromUnlockedToUnlocked": false,
            "lockFromLockedToLocked": false,
            "unlatchLock": true,
            "unlatchLockPreventUnlatchIfLocked": false
        }
    ],
    "isApiEnabled": false,
    "apiPort": 40011,
    "apiToken": ""
}`

**Comment by lukasroegner** [comment]
> Erst wenn die Homebridge neugestartet wird aktualisiert sich der Status.

It seems that the callback mechanism does not work properly. Have you checked option b) from my previous post to see whether other updates are propagated to the plugin?

**Comment by Sheldor81** [comment]
Der Status des Schloss wird nicht an Homekit weiter gegeben.

**Comment by lukasroegner** [comment]
Ok, then check the logs when starting up Homebridge. There should be an entry

```
Callback already registered.
```

or

```
Callback registered.
```

If that is not the case, it might be that you have already registered the maximum number of callbacks on the Nuki bridge (3 at maximum), e.g. by other plugin or other integrations.

You can check that by sending an HTTP GET request to the bridge:
```
http://XXX.XXX.XXX.XXX:8080/callback/list?token=YYYYYY
```

where `XXX.XXX.XXX.XXX` is the Nuki bridge IP address and `YYYYYY` is the Nuki bridge token.

**Comment by Sheldor81** [comment]
[NukiPlatform] Device with Nuki ID XXXXXX and name Haustür is a SmartLock.
26.5.2020, 17:31:00 [NukiPlatform] Adding new accessory with Nuki ID XXXXX and kind LockAccessory.
26.5.2020, 17:31:00 [NukiPlatform] 407663549 - Updating lock state: UNSECURED/UNSECURED
26.5.2020, 17:31:00 [NukiPlatform] 407663549 - Updating latch state: SECURED/SECURED
26.5.2020, 17:31:00 [NukiPlatform] 407663549 - Updating critical battery: false

**Comment by Sheldor81** [comment]
{"callbacks": [{"id": 0, "url": "http://192.168.1.11:40506"},{"id": 1, "url": "http://192.168.1.11:51827/"},{"id": 2, "url": "http://192.168.1.11:51827:40506"}]}

Die "IP-Adresse" ist falsch es müsste die 192.168.1.250 sein.

**Comment by lukasroegner** [comment]
The entries look like you started the plugin with incorrect settings in the past. To fix that, make the following HTTP calls:

```
http://XXX.XXX.XXX.XXX:8080/callback/remove?id=0token=YYYYYY
http://XXX.XXX.XXX.XXX:8080/callback/remove?id=1token=YYYYYY
http://XXX.XXX.XXX.XXX:8080/callback/remove?id=2token=YYYYYY
```

where XXX.XXX.XXX.XXX is the Nuki bridge IP address and YYYYYY is the Nuki bridge token.

This will remove all callbacks and the plugin is now able to register the correct callback when you restart it.

**Comment by Sheldor81** [comment]
Wenn ich die Befehle ausführe kommt folgende Fehlermeldung:

HTTP 401 Unauthorized

**Comment by lukasroegner** [comment]
Sorry, missing character, should be the following requests:

```
http://XXX.XXX.XXX.XXX:8080/callback/remove?id=0&token=YYYYYY
http://XXX.XXX.XXX.XXX:8080/callback/remove?id=1&token=YYYYYY
http://XXX.XXX.XXX.XXX:8080/callback/remove?id=2&token=YYYYYY
```

**Comment by Sheldor81** [comment]
perfekt, vielen Dank. Jetzt funktioniert es.

Danke!!!
