### ISSUE TITLE
help with setting up

### ISSUE THREAD

**Issue by fdrolorin** [lukasroegner/homebridge-nuki#36]
Hi,

I am an extreme noob with these kind of things but I really want to get both my Ring Doorbell and Nuki Smart Lock to work together. My apologies if I ask stupid questions.

Below is my config, I currently get “Error while communicating with the Nuki Bridge. Status Code: 403” in the log of the Homebridge.

I also don’t understand in the setup text where how I should find the nuki-id and the apitoken?

Can I leave the nukiid on “0” as in the setup example?

Can I leave the apitoken on “0” if I don’t want to use the HTTP API?

Hope you can help me out and many thanks for building this in Homebridge.

{
            "platform": "NukiPlatform",
            "hostNameOrIpAddress": “<HOST-IP>“,
            "hostCallbackApiPort": 40506,
            "bridgeIpAddress": “<BRIDGE-IP>“,
            "bridgeApiPort": 8080,
            "bridgeApiToken": “<BRIDGE-TOKEN>",
            "bridgeRebootSwitch": false,
            "devices": [
                {
                    "nukiId": 0,
                    "isRingToOpenEnabled": true,
                    "isContinuousModeEnabled": false,
                    "isSingleAccessoryModeEnabled": true,
                    "unlatchFromLockedToUnlocked": true,
                    "unlatchFromUnlockedToUnlocked": true,
                    "lockFromLockedToLocked": false,
                    "unlatchLock": false,
                    "unlatchLockPreventUnlatchIfLocked": false
                }
            ],
            "isApiEnabled": false,
            "apiPort": 40011,
            "apiToken": “0“
        }

**Comment by lukasroegner** [comment]
@fdrolorin GitHub issues are not really the correct place to ask beginner questions, I highly suggest to go to Homebridge forums, where help if provided by a large community (e.g. SmartApfel if you live in Germany/Austria/Switzerland).

I'll try to give you a hint in the right direction (from the README):
You have to enable the HTTP API on the Nuki Bridge:
1. Open the Nuki app
2. Open the menu and go to "Manage my devices" and choose the Bridge
3. Click on "Manage bridge" and follow the instructions (press the button on the bridge for at least 10 seconds)
4. After the bridge management interface is loaded, click on the bridge icon and enable the switch for "HTTP API"
5. The IP address, port and API token are shown (you need them for the configuration of the plugin)

**Comment by fdrolorin** [comment]
Hi Lukas,

My bad, I will try the forum. I followed all the steps in the readme file (including the one that you just send me but it gives an error and i asked the questions because those two parameters aren’t clearly explained in the readme file so others might have the same issues. 

Kind regards,

Floris

**Comment by lukasroegner** [comment]
Hi @fdrolorin,

If you have the step "Prepare Bridge" properly configured, you can start the plugin with minimal configuration:

```
{
    "platforms": [
        {
            "platform": "NukiPlatform",
            "hostNameOrIpAddress": "<HOST-IP-OR-NAME>",
            "bridgeIpAddress": "<BRIDGE-IP-ADDRESS>",
            "bridgeApiToken": "<BRIDGE-API-TOKEN>",
            "bridgeRebootSwitch": false,
            "devices": []
        }
    ]
}
```

<HOST-IP-OR-NAME>: the IP address of the device you are running Homebridge on
<BRIDGE-IP-ADDRESS>: from within the Nuki app (as described in "Prepare Bridge")
<BRIDGE-API-TOKEN>: from within the Nuki app (as described in "Prepare Bridge")

Now, you can start Homebridge, the plugin will print out the Nuki ID of your lock in the logs. Now, you can fill out the devices array (copy the Nuki ID from the logs) and restart Homebridge.
