### ISSUE TITLE
is it possible the battery status display at homekit?

### ISSUE THREAD

**Issue by testpaul999** [lukasroegner/homebridge-nuki#4]
Hallo,

if you ask the ip:port/list?token=xxxx you get 

batteryCritical | false

can this information displayed in homekit?
regards

**Comment by felixmueller** [comment]
Hello @testpaul999,

this would be a very nice feature!

@lukasroegner If you need some inspiration on how to implement battery status and battery warnings, this plugin just got this feature: https://github.com/meg768/homebridge-ikea-tradfri-gateway.

Cheers
Felix

**Comment by lukasroegner** [comment]
New version 0.4.0 online and on NPM. I did not add the `BatteryService` as this service requires percentage of the battery. However, there is a `BatteryLow` characteristic, which works in HomeKit when added to a lock service. Here are the results:

Normal battery status (nothing visible):
![IMG_0004](https://user-images.githubusercontent.com/16758848/65385809-2710e500-dd33-11e9-96cb-80b7c87b2ef1.png)

Low battery status (exclamation mark icon + red label):
![IMG_0005](https://user-images.githubusercontent.com/16758848/65385815-3abc4b80-dd33-11e9-849f-aa1cfd71363c.png)

Details view ("Battery low" in the status label on the top):
![IMG_0006](https://user-images.githubusercontent.com/16758848/65385822-49a2fe00-dd33-11e9-8e55-1928ed614fe0.png)

Advanced details ("Battery low" at the top):
![IMG_0007](https://user-images.githubusercontent.com/16758848/65385823-57588380-dd33-11e9-9242-e0dcbf7e412a.png)

**Comment by testpaul999** [comment]
Danke, werde ich heute Abend testen.

 Grüße

Jens-Uwe

Am 22.09.2019 um 12:20 schrieb Lukas Rögner <notifications@github.com>:

﻿

New version 0.4.0 online and on NPM. I did not add the BatteryService as this service requires percentage of the battery. However, there is a BatteryLow characteristic, which works in HomeKit when added to a lock service. Here are the results:

Normal battery status (nothing visible):
[IMG_0004]<https://user-images.githubusercontent.com/16758848/65385809-2710e500-dd33-11e9-96cb-80b7c87b2ef1.png>

Low battery status (exclamation mark icon + red label):
[IMG_0005]<https://user-images.githubusercontent.com/16758848/65385815-3abc4b80-dd33-11e9-849f-aa1cfd71363c.png>

Details view ("Battery low" in the status label on the top):
[IMG_0006]<https://user-images.githubusercontent.com/16758848/65385822-49a2fe00-dd33-11e9-8e55-1928ed614fe0.png>

Advanced details ("Battery low" at the top):
[IMG_0007]<https://user-images.githubusercontent.com/16758848/65385823-57588380-dd33-11e9-9242-e0dcbf7e412a.png>

**Comment by testpaul999** [comment]
Ich versuche das über config-ui zu installieren und bekomme diesen Fehler.
[cid:2A681CCD-F86F-4C3B-929F-A2B577669FF1-L0-001]

?

Danke
Grüße

Jens-Uwe

Am 22.09.2019 um 12:20 schrieb Lukas Rögner <notifications@github.com>:

﻿

New version 0.4.0 online and on NPM. I did not add the BatteryService as this service requires percentage of the battery. However, there is a BatteryLow characteristic, which works in HomeKit when added to a lock service. Here are the results:

Normal battery status (nothing visible):
[IMG_0004]<https://user-images.githubusercontent.com/16758848/65385809-2710e500-dd33-11e9-96cb-80b7c87b2ef1.png>

Low battery status (exclamation mark icon + red label):
[IMG_0005]<https://user-images.githubusercontent.com/16758848/65385815-3abc4b80-dd33-11e9-849f-aa1cfd71363c.png>

Details view ("Battery low" in the status label on the top):
[IMG_0006]<https://user-images.githubusercontent.com/16758848/65385822-49a2fe00-dd33-11e9-8e55-1928ed614fe0.png>

Advanced details ("Battery low" at the top):
[IMG_0007]<https://user-images.githubusercontent.com/16758848/65385823-57588380-dd33-11e9-9242-e0dcbf7e412a.png>

**Comment by lukasroegner** [comment]
@testpaul999 Image is not attached in your post. Please try to use GitHub and upload the image by dragging & dropping.

**Comment by felixmueller** [comment]
@lukasroegner Awesome, thank you for the quick implementation of the battery warning feature!

**Comment by testpaul999** [comment]
Sorry please here 
![IMG_1790](https://user-images.githubusercontent.com/35597907/65389366-b8914e80-dd55-11e9-9cdc-9b30b6929672.png)

**Comment by lukasroegner** [comment]
Checked by installing latest version on a test setup, works as expected.

Based on the error message I also double-checked the package.json and ran it through a JSON validator, everything is fine.

When I google your issue, people ofter recommend `npm cache clean`.

**Comment by testpaul999** [comment]
hi,

if i install by hand it works.
but the plugin will be installed at the "worng" path.

your plugin /usr/local/lib/node_modules
all other
/usr/lib/node_modules

regards Jens

On Sun, 22 Sep 2019 07:39:22 -0700
Lukas Rögner <notifications@github.com> wrote:

> Checked by installing latest version on a test setup, works as expected.
> 
> Based on the error message I also double-checked the package.json and ran it through a JSON validator, everything is fine.
> 
> When I google your issue, people ofter recommend `npm cache clean`.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/lukasroegner/homebridge-nuki/issues/4#issuecomment-533887660


-- 
Jens <jufranz@outlook.com>

**Comment by lukasroegner** [comment]
Have you tried to clear the NPM cache?

**Comment by testpaul999** [comment]
Sure dos not help. Only at cli install sudo npm install Homebridge-nuki -g runs.
If I’ll try via config-Ui it fails.

Liebe Grüße

Jens-Uwe

Am 22.09.2019 um 17:08 schrieb Lukas Rögner <notifications@github.com>:

﻿

Have you tried to clear the NPM cache?

**Comment by testpaul999** [comment]
Hi, have found my issue there was a empty package.json in the path /usr/lib/ .
I'll remove this and now ich can install with the config-ui the package.

Regards

On Sun, 22 Sep 2019 08:08:06 -0700
Lukas Rögner <notifications@github.com> wrote:

> Have you tried to clear the NPM cache?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/lukasroegner/homebridge-nuki/issues/4#issuecomment-533889886


-- 
Jens <jufranz@outlook.com>
