### ISSUE TITLE
Is the Nuki Bridge required?

### ISSUE THREAD

**Issue by nixmeer** [lukasroegner/homebridge-nuki#40]
Hello, 

I didn’t not find any other information, so I guess I’ll need to buy the bridge, right? There is no way to use the raspberry pi’s Bluetooth, right?

Best

Jan

**Comment by lukasroegner** [comment]
Hi @nixmeer,
Indeed, you'll need to buy the bridge to use the plugin. The plugin works locally, i.e. the local bridge API is used, not the web API.

**Comment by nixmeer** [comment]
Ok thank you. Locally means I can block the internet connection for the bridge and the lock and still use it? The plugin communicates over http, right? Can just any device in the local network send these http requests?

**Comment by lukasroegner** [comment]
Theoretically, you could block the internet connection. The bridge API uses HTTP in combination with an authentication token.

**Comment by nixmeer** [comment]
Thanks!
