### ISSUE TITLE
Nuki beta: Nuki Bridge API: Bell Ring of Nuki Opener as Trigger for Callbacks

### ISSUE THREAD

**Issue by beatpaul** [lukasroegner/homebridge-nuki#42]
Hi!

Your feature request „Nuki Bridge API: Bell Ring of Nuki Opener as Trigger for Callbacks“ finally(!!!) is in the nuki Beta FW
Will there be an implementation in this plugin soon?

Thx for your work!!
All the best

**Comment by lukasroegner** [comment]
Hi @beatpaul,

The feature is now implemented, just set `isDoorbellEnabled` to `true` to receive Apple Home app notifications.

**Comment by felixmueller** [comment]
Hi @lukasroegner,

thank you very much for implementing this feature so quickly!

How is the doorbell supposed to work? I see a new accessory in Homebridge but not in the Home App. Should the doorbell be visible somewhere in the Home App?
Can the notifications be controlled separately from the ones from the lock itself? I want to get doorbell notifications when I am at home, but other notifications (e.g. Auto Unlock on RTO) when I am not at home.

Thank you for clarification!

Cheers,
Felix

**Comment by lukasroegner** [comment]
Hi @felixmueller,

The Doorbell service is some kind of invisible service that can be added to accessories.
In this case, the Doorbell service is added to the main accessory (where the lock service resides).

The doorbell rings if the callback of the Nuki Bridge reports `ringactionState=true`, which is the case of someone rings the bell (not triggered for RTO unlocks).

I don't see any solution to manage the notifications separately, as there is only one switch for notifications per accessory.
The Doorbell cannot reside in a separate accessory, it always needs a visible service to be bound to. Maybe you have an idea?

**Comment by felixmueller** [comment]
Hi @lukasroegner,

I have no idea so far, thank you very much. I think we have to wait how it works in practice. The new bridge firmware is still in beta if I got it correctly.

Speaking of the bridge firmware: could the battery percentage be implemented, too?
https://developer.nuki.io/t/bridge-beta-fw-2-7-0-1-17-0/6792

_get the battery in % for a Smart Lock (experimental)
(needs Smart Lock Firmware 2.8.1/1.10.0 or higher)_

**Comment by lukasroegner** [comment]
OK, so I'm closing this issue for now, feel free to re-open if you have an idea on how to enhance it.

> Speaking of the bridge firmware: could the battery percentage be implemented, too?

Sure, please create a separate issue for that.

**Comment by Nastras** [comment]
Hello lucas,

i have not tested the new function yet but will do it later. If I understand it correctly is an automation with the new function not possible to use the ringing as a trigger because no extra sensor is created?

Only one push message is created by the Home App?

**Comment by lukasroegner** [comment]
@Nastras Have you tried the Eve app? I think that the Eve app shows the doorbell as a stateless switch, so it should be possible to use the switch as a trigger in automations.

**Comment by Nastras** [comment]
Yes, I did. I'm not getting a reading. But I am also not shown at the plugin start that the function was added?

![C1C4BCC1-CA59-4B5A-A272-DDB27A722078](https://user-images.githubusercontent.com/27686185/89861335-d05c0600-dba5-11ea-9991-ca54ca38ae12.jpeg)
![CD24AC3E-B8DF-4178-80E4-D0E0B7B744D5](https://user-images.githubusercontent.com/27686185/89861339-d2be6000-dba5-11ea-8cdc-e1ed83eb6b0b.jpeg)
![68AB5A44-AA2C-49CF-9772-D72F41D06052](https://user-images.githubusercontent.com/27686185/89861340-d3ef8d00-dba5-11ea-8763-5a01837fc506.jpeg)

**Comment by lukasroegner** [comment]
It is shown in Eve and you can add it to automations (the push button icon in the list on you screenshot).
I tested it with the Eve app: when creating a new rule, the doorbell is shown as a push button.

**Comment by Nastras** [comment]
I found it. Now I just have to install the beta later and then it should work?Thank you!

**Comment by lukasroegner** [comment]
I've also only tested it with some test code and it works as expected. I'm not in the Beta program as this is my daily driver.

**Comment by Nastras** [comment]
Im not at home for the rest of the week. I will test it on the weekend. Thanks Lukas for the quick help .-)

**Comment by Nastras** [comment]
Hi Lukas,

i just tried it out and added the opener switch to my trigger by simply pressing it. Unfortunately it does not work. The automation is not executed after a ringing. I have no beta installed.

Do you have an idea, if not I will wait until the new Nuki firmware is stable.

Thanks!

![4996428C-42DA-4F39-B48A-2D05F3E59747](https://user-images.githubusercontent.com/27686185/90334620-4362e380-dfcf-11ea-8967-9a4c9476282a.jpeg)

**Comment by lukasroegner** [comment]
> I have no beta installed.

This only works for the latest Bridge Firmware Beta

**Comment by Nastras** [comment]
So yes, I understood you above that it also works without beta firmware. Then I wait until it is officially available.

Have a nice sunday ;-)
