### ISSUE TITLE
Bridge Beta FW 2.7.0 / 1.17.0: Implement battery in percent for SmartLock

### ISSUE THREAD

**Issue by felixmueller** [lukasroegner/homebridge-nuki#43]
It would be great to get the the battery percentage of the SmartLock accessory displayed in the Home App.

The Bridge Beta FW 2.7.0 / 1.17.0 seems to return the percentage:
https://developer.nuki.io/t/bridge-beta-fw-2-7-0-1-17-0/6792

_get the battery in % for a Smart Lock (experimental)
(needs Smart Lock Firmware 2.8.1/1.10.0 or higher)_

Thank you very much for considering implementing this!

**Comment by lukasroegner** [comment]
Implemented in 0.10.0!

**Comment by felixmueller** [comment]
> Implemented in 0.10.0!
Awesome - thank you so much! 👏
