### ISSUE TITLE
Opener: Auto Lock after some seconds

### ISSUE THREAD

**Issue by Marfre888** [lukasroegner/homebridge-nuki#44]
Hi,

I have just installed this plugin. So far it's working great.

I have a gate at my property which I use the opener for. I've noticed that the default for this plugin is to set the tile back to the locked position after a few seconds of being opened.

Is it possible to stop it from doing that? I have a door sensor connected to it, and I'd like to set the locked state when the gate is actually closed, so I know if the gate has been left open or not, if it is ever accidentally triggered by homekit.

Thanks.

**Comment by lukasroegner** [comment]
Implemented in 0.10.1. There is a new parameter `leaveOpen` that you can set to `true`.

**Comment by Marfre888** [comment]
Thank you :)

**Comment by Marfre888** [comment]
@lukasroegner Update works great. It doesn't lock until gate closes, however homekit now is getting stuck on 'Locking' and doesn't actually set the door to a locked state.

![05d253ac-655b-4c3c-bfba-dbfe5ca09dd8](https://user-images.githubusercontent.com/63603736/90274885-a8003000-de61-11ea-8df0-65f846bc0e9e.jpg)

**Comment by lukasroegner** [comment]
Should work now in the latest version 0.10.2.

**Comment by Marfre888** [comment]
@lukasroegner Working great now. Thank you for much
