### ISSUE TITLE
Two Nuki Devices / IDs

### ISSUE THREAD

**Issue by clipse2004** [lukasroegner/homebridge-nuki#45]
Hi dude,

I have more devices like lock, opener etc. Now I have two Nuki IDs and when I add a second Line with "Nuki ID": xxx it will be automatic delete.
How can I add a second device? 

Thanks for your help!!

**Comment by lukasroegner** [comment]
Hi @clipse2004,

You need to add the device part for each device, i.e.
```
{
  "nukiId": XXX,
  ...
},
{
  "nukiId": YYY,
  ...
}
```

**Comment by clipse2004** [comment]
thanks dude i forgot to delete some , :/
i have a last question, now he show me my lock and my opener but i get these message:
15:31:50 - HAP Warning: Characteristic 00000079-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000045-0000-1000-8000-0026BB765291. Adding anyway.

is this important? or can i ignore it?

**Comment by lukasroegner** [comment]
Can be ignored, it means that the plugin uses a characteristic in a way that is it not intended to be used. Works, however, even in the Apple Home app.

**Comment by clipse2004** [comment]
ah okay thanks =)
