### ISSUE TITLE
Battery state with version 0.10.1 at 0%

### ISSUE THREAD

**Issue by testpaul999** [lukasroegner/homebridge-nuki#46]
Hi,thx for your helpful plugin.
I'm surprised for the battery level, but it don't work for me.
I see only 0% 
![IMG_2129](https://user-images.githubusercontent.com/35597907/90216840-efee6b00-ddff-11ea-84da-8a6dcf56c205.PNG)

i run the version homebridge-nuki v0.10.1 

regards

**Comment by lukasroegner** [comment]
Are you running the latest Beta (https://developer.nuki.io/t/bridge-beta-fw-2-7-0-1-17-0/6792)?

**Comment by testpaul999** [comment]
Sorry, no have the release version run.
So you can close this request. 🙂

**Comment by testpaul999** [comment]
Thx
