### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by derthobo** [lukasroegner/homebridge-nuki#48]
Is it possible to expose a sensor (contact or motion) for the doorbell (Opener)?

I'm getting a notification if someone ring the doorbell. But I can't use it for i.e. in an automation.

Thanks for your great work. With your plug-in the Nuki-solution has such more value! :)

**Comment by lukasroegner** [comment]
You can create the automation in the Eve app: the doorbell is shown as a stateless switch and can be used as a trigger for automations (see #42).

**Comment by derthobo** [comment]
Perfect. It works! Thank you for your quick reply! :)
