### ISSUE TITLE
Change of status is not recognized

### ISSUE THREAD

**Issue by MikeDeltaHH** [lukasroegner/homebridge-nuki#49]
Good morning!
Recently I've been getting more and more often the problem that the plugin doesn't implement the change of the statute of the Nuki! I have two automations in my settings, one that should be done when I leave the house - door should be locked, all lights off and camera on and one that should be done when I come back home - when I leave the house the door is locked and the plugin shows the corresponding status - but when I come back home the door is unlocked, this status is shown in the Nuki, all automations work but in Homebridge the door is still shown as "closed" - I have to restart Homebridge for the plugin to recognize the correct status! In the Homebridge log I can't find anything that indicates an error... can you help me here?

Here is my config for it:

{
"bridgeApiPort": 8080,
"bridgeApiToken": "xxx",
"bridgeIpAddress": "xxx",
"bridgeRebootSwitch": true,
"devices": [
{
"isContinuousModeEnabled": false,
"isRingToOpenEnabled": false,
"nukiId": xxx,
"unlatchFromLockedToUnlocked": false,
"unlatchFromUnlockedToUnlocked": false,
"unlatchLock": false
}
],
"hostCallbackApiPort": 40506,
"hostNameOrIpAddress": "xxx",
"platform": "NukiPlatform",
"plugin_map": {
"plugin_name": "homebridge-nuki"
}

Regards!
Mike

**Comment by lukasroegner** [comment]
If you've played around with the plugin or other plugins/programs/etc. that use the Bridge API and the callback feature, there is a chance that all 3 callback URLs on the Bridge are already set. You can check this by calling the `/callback/list` endpoint. 

Here is post of a user that had a similar problem (incl. solution): https://github.com/lukasroegner/homebridge-nuki/issues/47#issuecomment-675313195

**Comment by thecem** [comment]
may a hint in the readme.md should be usefull:

**hostNameOrIpAddress:** The IP address or host name of the device you run the plugin on. This information is required to register a callback for notifications. (be aware in the bridge only 3 callback are registrable, if you have changed to a new host pls check: #47)

**Comment by lukasroegner** [comment]
Added a paragraph to the README.
