### ISSUE TITLE
Question: callback from Opener „ring notification“ to HomeKit taking very long

### ISSUE THREAD

**Issue by CooperCGN** [lukasroegner/homebridge-nuki#50]
Hi Lukas,

I know it’s still beta firmware for the opener and the bridge but the callback seems to take forever like 15 to 20 seconds till the ring notification comes up in HomeKit. Just wondering whether it’s the opener, bridge or the plugin. Is it maybe even a local problem in my configuration. Any idea?

**Comment by lukasroegner** [comment]
Hi @CooperCGN, 

I'm not enrolled in the beta program, thus, I haven't tested out the implementation, yet.
However, there are some users that already tested the plugin with the beta firmware (#42), e.g. @Nastras, maybe he can tell us how long the delay is in his configuration.

**Comment by Nastras** [comment]
Hello everyone, I can't tell you anything about it because I'm not participating in the beta program either. I am also waiting for the official release. Sorry.

**Comment by CooperCGN** [comment]
Guess we have to wait then, thanks for the feedback.

**Comment by CooperCGN** [comment]
I think we can close this for now, I think I found the problem. I had a callback url still registered on my bridge from an old installation previous to the Nuki lock 2.0 which ran into a non existent port. This may have caused the bridge to wait for a timeout before calling the second callback url triggering the bell notification. Will do some further testing but for now it seems solved.

**Comment by CooperCGN** [comment]
I still have some long delays between the actual ring and the notification popping up. I decided to do some manual testing. What would I need to add to the callback url when calling it from the command line? I guess it is some JSON I have to add? I just want to make sure it’s not my Pi but maybe the nuki opener causing this, so I can give feedback to the Nuki guys.

**Comment by lukasroegner** [comment]
Basically, you need a receiver for the callback, i.e. some sort of HTTP server that can receive the HTTP request from the Nuki Bridge. Then, register the URL of this HTTP server via `http://<1>:8080/callback/add?url=<2>&token=<3>` with:
- `<1>`: the IP address of the Nuki Bridge
- `<2>`: the URI encoded URL of your HTTP server
- `<3>`: the token for the Nuki Bridge

**Comment by CooperCGN** [comment]
Thanks, but I think you didn’t exactly got it what I am trying to do. I want to make a manual call towards your plugin so I don’t have to run downstairs (5 levels) to push the actual ring button.

Off topic: I think we might need a fake camera accessory in the future for the opener. For testing purposes I updated one of my HomePods to 14.2 and now whenever someone rings that HomePod plays a chime, a new feature introduced with 14.2 
As far as I got it this can be (de-)activated in the doorbell camera.

**Comment by lukasroegner** [comment]
> Thanks, but I think you didn’t exactly got it what I am trying to do. I want to make a manual call towards your plugin so I don’t have to run downstairs (5 levels) to push the actual ring button. I have the callback link from the bridge.

If you just want to try out the delay of the plugin, you can send the HTTP call that the Nuki Bridge would send (i.e. replay the HTTP request). The specs of the body of the request can be found in the bridge documentation of Nuki.

**Comment by CooperCGN** [comment]
OK will check there again. Thanks

**Comment by Nastras** [comment]
I updated all Nuki stuff yesterday. My homepods are already on 14.2 beta.

I now get a message from the home app when it rings and I can set triggers when it rings.
@lukasroegner Good work 👍

My experience with the ringing of the homepod is that it does not work reliably. I have 9 homepods in use and the ringing is a bit delayed. Also, not all homepods ring and it varies.

A function to deactivate or select which homepods are ringing is still missing.

**Comment by CooperCGN** [comment]
In this video at around minute 17 you can see that the doorbell has a switch for the HomePod chime, I suspect the corresponding switch on the HomePod shown later in the vid is only popping up if the HomePod sees a doorbell accessory in the setup.

https://www.youtube.com/watch?v=ZPA1FgW95rg

**Comment by Nastras** [comment]
I've seen it. I do not have this switch because the opener is shown as a door. I am surprised that the homekit still recognizes the ringing?

Do you see a possibility to show the opener as a bell like in the video to show the option?

**Comment by CooperCGN** [comment]
Now I am totally confused, all I see for the opener itself is a lock which unlocks the basements entry door.

Anyway I did some manual testing and can say that there is no noticeable delay between the callback and the message on the iOS devices. My HomePods chime instantly. Guess Nuki had to improve the callback from the opener, 15 to 20 seconds is too much for me.
