### ISSUE TITLE
Automation with ring notification?

### ISSUE THREAD

**Issue by beatpaul** [lukasroegner/homebridge-nuki#53]
Hi!
Is there a way to do automations with the ring notification of the Opener?
E. g. if someone rings -> the light turns blue...

Maybe it would be nice to have a fake switch or Sensor that turns on when someone rings?

What do u think?

Thx for your great work!

**Comment by lukasroegner** [comment]
Hi @beatpaul, you can use the ring notification in automations, see #42, you just have to use a third-party HomeKit app to create the automation.

**Comment by beatpaul** [comment]
Thx for your quick response!
