### ISSUE TITLE
homebridge crashes when opener has no name

### ISSUE THREAD

**Issue by nixmeer** [lukasroegner/homebridge-nuki#56]
Hello :) thank you so much for doing the work I paid Nuki to do...

However, I spotted an issue which is not your fault but you might find a way to handle it. 

There is an Elcom BFT-200 in my flat which is not supported by the Nuki opener. So I had to try a lot and often times reset the opener and configure it over and over again. At some point I got it working by finding the correct signal paths on the pcb. But here's the thing: the name of the opener has been correctly shown on the starting page of the Nuki app but not in the administration section. That caused the opener to register at the bridge with no name. When this plugin tries to use this name as `displayName`, homebridge crashes. 

Maybe you could catch this case and check if the name is empty.

Best 

Jan

**Comment by lukasroegner** [comment]
Thanks for reporting, fixed in latest version!
