### ISSUE TITLE
Doorbell registrations and open by notifications

### ISSUE THREAD

**Issue by carlsendk** [lukasroegner/homebridge-nuki#58]
Hi,

It is super we got notifications enable in the nuki API.

Are you up for doing the same trick as with Nello to open from notifications? Or should it just work if you have a camera in the same room?

2nd
![IMG_1282](https://user-images.githubusercontent.com/40060660/97583278-09628480-19f7-11eb-9b80-08b23bc4a759.PNG)

This under Home settings btw

I have a doorbell on my front door, but the nuki opner dosn't seems to be set as a doorbell in HomeKit is that because it dosn't have a video title attached?

I would think if you could get in there you could use a homepod to trigger a sound if someone rang.

Again thank you for the awesome work both with Nello and now this.

**Comment by carlsendk** [comment]
Or is this in the homebridge core i need to file an issue?

**Comment by CooperCGN** [comment]
My HomePods play the bell sound when someone is ringing. The opener does initiate the callback on the bridge which then triggers the HomePods.

**Comment by carlsendk** [comment]
@CooperCGN Nice can you see it under doorbell in the home app?

**Comment by CooperCGN** [comment]
No, I assume it would need a camera added, maybe a fake one.

**Comment by lukasroegner** [comment]
The HomePod notifications already work with this plugin, for support for tvOS, see #55.

**Comment by Manguera** [comment]
> The HomePod notifications already work with this plugin, for support for tvOS, see #55.

Hi there,

i´m running the latest version of this plugin and set "isDoorbellEnabled" to true but it doesn´t work. I have no setting in all homepods to enable them as a chime for the opener. Anything I forgott or missing?

Thanks and best
Markus

**Comment by felixmueller** [comment]
Hi @Manguera,

the HomePod chime seems to work with this plugin without any setting. I wrote about this a while ago: https://github.com/lukasroegner/homebridge-nuki/issues/55#issuecomment-715258226

Hope it works for you, too!

Best,
Felix
