### ISSUE TITLE
Restart the Nuki Bridge with an additional switch in Homekit

### ISSUE THREAD

**Issue by Nastras** [lukasroegner/homebridge-nuki#6]
Hello, lucas,
i tested your plugin today and it works very well. Many thanks for your great work!

Is it possible that you add a function with an additional switch in Homekit that allows you to restart the Nuki Bridge?

King regards,
Nastra

**Comment by lukasroegner** [comment]
Yes, can be implemented easily. I will add a configuration option so that you can enable/disable the switch for that. Do you have a suggestion on which type of accessory to use? Maybe a simple switch?

**Comment by felixmueller** [comment]
May I ask for the reason for a restart switch for the Bridge? Is it unstable and needs a restart from time to time? Sorry, I've only had the bridge for a few days and I'm having no issues/crashes so far.

**Comment by lukasroegner** [comment]
@felixmueller I suggest that @Nastras uses the Bridge with some other services and the Bridge actually has a huge issue with processing parallel requests: it can't do that. Moreover, the Bridge may hang for minutes if you send multiple requests at a time (or too many requests in sequence).

**Comment by Nastras** [comment]
Perfect! Yes, a simple switch. It would be great if the switch turns off automatically after activation.

Can you tell me if it is also possible to restart the bridge with a curl command?

@felixmueller 
I have already the case that the locks over the Nuki Bridge were no longer accessible but the bridge itself already. Therefore it would be good if you could restart the bridge without disconnecting it from the power supply.

**Comment by felixmueller** [comment]
@lukasroegner @Nastras Oh I see, thanks for your explanations!

**Comment by lukasroegner** [comment]
@felixmueller You can also take a look at the code (`NukiBridge` object), I had to implement some kind of queue and timeout for requests that are being sent to the Bridge.

**Comment by lukasroegner** [comment]
@Nastras Please try the `development` branch, I added a new configuration parameter `bridgeRebootSwitch` (set to `true` to enable the reboot switch).

**Comment by Nastras** [comment]
Hello Lukas, i just tested it, it works very well. Super that the plugin doesn't throw out any errors when rebooting the bridge.

I think you can release the version.

Thanks a lot for the quick implementation !

**Comment by lukasroegner** [comment]
Merged in #8 and new version 0.5.0 on NPM.
