### ISSUE TITLE
Device with Nuki ID in HEX Value not accepted (even not in Hombridge UI)

### ISSUE THREAD

**Issue by thecem** [lukasroegner/homebridge-nuki#60]
HI,
I have a new White Edition Nuki Smart Lock witch have a ID like this 121F037C, the config is not accepted this and even is not shown after initial load. So I think the Nuki ID could not longer a string value.

Config:  
```
{
  "nukiId": 121F037C,
  "isDoorSensorEnabled": true,
  "isSingleAccessoryModeEnabled": true,
  "unlatchFromUnlockedToUnlocked": true
 },
```
could this be changed, to have the new locks with hex value ID in HB?

If you need additional information let me know.

Thanks a lot!

**Comment by lukasroegner** [comment]
The `nukiId` has to be the ID coming from the Bridge, not the serial number or the ID on the web, take a look at the README: https://github.com/lukasroegner/homebridge-nuki#find-nuki-ids-of-the-devices

**Comment by thecem** [comment]
Thanks a lot, but do I have to de configure already installed and configured devices to add a new one?

**Comment by lukasroegner** [comment]
If you provided the config like shown above, Homebridge won't load as this is not valid JSON. I suggest removing the part of the config that you posted above, restart Homebridge, then check the logs for the actual ID that is coming from the Bridge.

**Comment by thecem** [comment]
This was the plan, I started with the old working config 1 Opener and 2 SmartLocks but the new one was not shown up, after a restart of HB. Anyway the lock is now working.
