### ISSUE TITLE
"isDoorbellEnabled": true, Not exposing doorbell

### ISSUE THREAD

**Issue by SteeeveAT** [lukasroegner/homebridge-nuki#66]
Hi. 

Today I added "isDoorbellEnabled": true, to the configuration, sadly the opener does not show up in the doorbell configuration of homekit. The opener was already used in homekit before I added this line.

Thanks 

Steve

**Comment by Tweak1981** [comment]
Today i installed this Plugin and i have the same problem/question. The opener appears in HomeKit and i can set ring to open and continuous mode. In Homebridge the "doorbell" is listed, but not in HomeKit. 
Any ideas? Homebridge, the Plugin, iOS... all are up-to-date.

**Comment by dankowee** [comment]
You could use the myHome or Eve app where the doorbell is visible as a Button and set up a dummy switch to integrate it in Home.

**Comment by Tweak1981** [comment]
> You could use the myHome or Eve app where the doorbell is visible as a Button and set up a dummy switch to integrate it in Home.

Nope... the Eve app doesn't show the doorbell in any room. Only Homebridge UI list the doorbell as device.
<img width="710" alt="homebridge" src="https://user-images.githubusercontent.com/41558173/102720506-06985780-42f5-11eb-9497-8db5386253f5.png">

In the HomeKit section for Camera and Doorbell is only my Cam from the living room listet (the doorbell should appear there).
![FullSizeRender](https://user-images.githubusercontent.com/41558173/102720658-f7fe7000-42f5-11eb-9089-788226b2f359.jpg)

**Comment by dankowee** [comment]
The doorbell is exposed in the sub menu of your opener in the Eve app. 
![EEEDA1C8-7723-4CC0-9BA4-597ABBDC82D9](https://user-images.githubusercontent.com/46874564/102721589-08194e00-42fc-11eb-84f1-0d2d592b22cb.jpeg)
![5CEC2712-7BB8-4233-8143-A05FEA8552DF](https://user-images.githubusercontent.com/46874564/102721592-09e31180-42fc-11eb-8238-e524bc4fbc92.jpeg)

**Comment by Tweak1981** [comment]
OK, found it :) thx
But how can i integrate it, so that's listet as doorbell in HomeKit and the HomePods play a chime sound?

**Comment by dankowee** [comment]
Just set up a dummy switch, tell your doorbell switch to control that dummy in Eve, and control everything else in homekit with that dummy switch. 
For the chime sound just enable notifications for the door in homekit settings. 
![F9458C75-F12E-47D6-BB87-BA15B50BAED7](https://user-images.githubusercontent.com/46874564/102723130-592e3f80-4306-11eb-90ed-6aa5f42d6c69.jpeg)
![CA9CEB1F-6087-4AF6-ACF4-0679ADF862CF](https://user-images.githubusercontent.com/46874564/102723131-5a5f6c80-4306-11eb-885b-4de7e91ba964.jpeg)

**Comment by DrawringSimon** [comment]
> Just set up a dummy switch, tell your doorbell switch to control that dummy in Eve, and control everything else in homekit with that dummy switch.
> For the chime sound just enable notifications for the door in homekit settings.
I'm probably missing some steps here. Downloaded the Eve app, see the doorbell, added a dummy switch accessory to Homebridge. Maybe this is too advanced for me, but I'm not seeing how to put this all together. Is this the way this plugin is supposed to work, or is it supposed to show up in Homekit with just the Nuki plugin?

**Comment by dankowee** [comment]
This plugin should expose every component you defined as true to homekit, but your doorbell will only show up in "Doors & Locks" in the settings. 
For your Eve rule: did you activate it? If yes, try something else as a trigger just to see if the rule itself works.

**Comment by DrawringSimon** [comment]
Thanks for replying. Yes, I checked that it's enabled. And I tried a smart light in addition to the dummy switch to see if it triggers. Attached the image to show my setup but maybe I'm doing something obviously wrong?
![IMG_9721](https://user-images.githubusercontent.com/68092662/103044068-f4f0c300-4533-11eb-842f-233f4a2634f4.jpg)

**Comment by lukasroegner** [comment]
If the issue still persists, feel free to re-open, closing for now.
