### ISSUE TITLE
Setup difficulties

### ISSUE THREAD

**Issue by samydoesit** [lukasroegner/homebridge-nuki#67]
Hello @lukasroegner,

i have difficulties setting this one up.
My setup looks like that:
```javascript
{
            "platform": "NukiPlatform",
            "hostNameOrIpAddress": "***",
            "bridgeApiPort": 8080,
            "bridgeIpAddress": "***",
            "bridgeApiToken": "***",
            "bridgeRebootSwitch": false,
            "devices": [
                {}
            ]
        }
```
should this work as an initial Setup?

After restarting Homebridge i get the following Errors:
`[NukiPlatform] Error while communicating with the Nuki Bridge. Error: Error: connect ETIMEDOUT <IPAdress of NukiBridge>:8080`

Any ideas? If i do a manual ping from the rpi everything is working correctly no package lost.

If i understood correct, after a restart this plugin should print out all devices in the logs?

When i first tried there was a callback registered at nuki bridge,  i removed it, since then there gets no new no callback registered at nuki bridge. I tried it by ip and hostname.

**Comment by dankowee** [comment]
"hostNameOrIpAddress" should be the IP of the device you're running this plugin on, e.g. I'm using a Raspberry Pi, so I use my Pis IP.

**Comment by dankowee** [comment]
"hostCallbackApiPort" is missing.

**Comment by samydoesit** [comment]
I added "hostCallbackApiPort" nothing changed.
After restarting homebridge this came across my homebridge logs:`
[15/12/2020, 19:51:43] [NukiPlatform] Initializing NukiPlatform platform...
[15/12/2020, 19:51:43] [NukiPlatform] Homebridge API available.
[15/12/2020, 19:51:43] [NukiPlatform] Cached accessories loaded. Server listening on: http://<ip>:8282
[15/12/2020, 19:56:24] [NukiPlatform] Error while communicating with the Nuki Bridge. Error: Error: connect ETIMEDOUT ***
`
On line 4 where it says "Server listening on: http://<ip>:8282" this is what gets printed in the console, the "<ip>" part looks not right to me. 
At nuki bridge no callback gets registered.

**Comment by dankowee** [comment]
Is any other device using the API port 8080?
Can you reach all your devices?
Have you installed the latest firmware?
Are all the values correct?

**Comment by jplab1983** [comment]
@samydoesit, I'm sure you have either solved it or given up already. But if there might be others in future also struggling, so here is how I solved the same issue.  

Make sure that, once you define an API key for the Bridge in the Nuki app, you don't forget to select "Save" and exit the Bridge in order for it to restart.  Also double-checking that the API key is correct helps :)

Anyway, not such a technical solution but in my case this stupid error could have same me a lot of time.
