### ISSUE TITLE
HAP Warning: Characteristic not in required or optional characteristics for service. Adding anyway.

### ISSUE THREAD

**Issue by Nastras** [lukasroegner/homebridge-nuki#7]
After the first start of homebridge-nuki a hap-warning is issued. Is this warning relevant?

Sep 23 13:17:14 HBS homebridge[12382]: [NukiPlatform] Cached accessories loaded.
Sep 23 13:17:14 HBS homebridge[12382]: Homebridge is running on port 51814.
Sep 23 13:17:15 HBS homebridge[12382]: [NukiPlatform] Device with Nuki ID xxxxxxxx and name Wohnungstürschloss 1 is a SmartLock.
Sep 23 13:17:15 HBS homebridge[12382]: [NukiPlatform] Adding new accessory with Nuki ID 374607085 and kind LockAccessory.
Sep 23 13:17:15 HBS homebridge[12382]: HAP Warning: Characteristic 00000079-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000045-0000-1000-8000-0026BB765291. Adding anyway.
Sep 23 13:17:15 HBS homebridge[12382]: [NukiPlatform] xxxxxxxx - Updating lock state: UNSECURED/UNSECURED
Sep 23 13:17:15 HBS homebridge[12382]: [NukiPlatform] xxxxxxxx - Updating latch state: SECURED/SECURED
Sep 23 13:17:15 HBS homebridge[12382]: [NukiPlatform] xxxxxxxx - Updating critical battery: false
Sep 23 13:17:15 HBS homebridge[12382]: [NukiPlatform] Device with Nuki ID xxxxxxxx and name Wohnungstürschloss 2 is a SmartLock.
Sep 23 13:17:15 HBS homebridge[12382]: [NukiPlatform] Adding new accessory with Nuki ID 371497181 and kind LockAccessory.
Sep 23 13:17:15 HBS homebridge[12382]: HAP Warning: Characteristic 00000079-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000045-0000-1000-8000-0026BB765291. Adding anyway.
Sep 23 13:17:15 HBS homebridge[12382]: [NukiPlatform] xxxxxxxx - Updating lock state: UNSECURED/UNSECURED
Sep 23 13:17:15 HBS homebridge[12382]: [NukiPlatform] xxxxxxxx - Updating critical battery: false
Sep 23 13:17:15 HBS homebridge[12382]: [NukiPlatform] Got devices from the Nuki Bridge API.
Sep 23 13:17:15 HBS homebridge[12382]: [NukiPlatform] Callback server started.
Sep 23 13:17:21 HBS homebridge[12382]: [NukiPlatform] Callback registered.

**Comment by lukasroegner** [comment]
This warning means that the lock service usually does not have a `BatteryLowStatus` characteristic. However, it is displayed in the Home app properly.

Can be ignored.

**Comment by Nastras** [comment]
All right, thanks for the quick answer!

**Comment by kouki31** [comment]
I have same thanks for answer.
