### ISSUE TITLE
'Serial Number' characteristic supplied illegal value in Homebridge 1.3.0

### ISSUE THREAD

**Issue by Marfre888** [lukasroegner/homebridge-nuki#71]
All in the title.

I'm beta testing Homebridge 1.3.0. As with a lot of other plugins, this plugin is kicking up this error.

![nuki](https://user-images.githubusercontent.com/63603736/108352471-2eb61100-71e7-11eb-8b6b-0eb9a8a95322.PNG)

Thanks so much for the work you do.

Mark

**Comment by redeemer666** [comment]
Hi Mark, does this issue prevents the plugin from working? I wanted to update my homebridge setup and this is the last plugin still not confirmed.

Thanks for your help

**Comment by Marfre888** [comment]
No, it works fine, it seems you only get this error while Homebridge is starting.

what I’m looking into is if there is a bug while this plugin is set as a child bridge, presently Siri is refusing to open the door for me

**Comment by redeemer666** [comment]
That’s great, this was the only plugin I didn’t know if it works with latest homebridge. Thanks a lot :)

**Comment by redeemer666** [comment]
Siri issue also here. If you ask Siri to lock or unlock nuKi doesn't receive the command. It only works manually inside the app

**Comment by mmz06** [comment]
> All in the title.
> 
> I'm beta testing Homebridge 1.3.0. As with a lot of other plugins, this plugin is kicking up this error.
> 
> ![nuki](https://user-images.githubusercontent.com/63603736/108352471-2eb61100-71e7-11eb-8b6b-0eb9a8a95322.PNG)
> 
> Thanks so much for the work you do.
> 
> Mark

Same issue for me as well.
I'm running Homebridge 1.3.4

**Comment by lukasroegner** [comment]
Fixed in 0.10.6.
