### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by Snub2000** [lukasroegner/homebridge-nuki#72]
Hello, I installed the Nuki plugin in Hoobs and configured it as follows:

{
    "platform": "NukiPlatform",
    "hostNameOrIpAddress": "192.xxx.x.xxx",
    "hostCallbackApiPort": 40506,
    "bridgeIpAddress": "192.xxx.x.xxx",
    "bridgeApiPort": 8080,
    "bridgeApiToken": "xxxxxx",
    "bridgeRebootSwitch": true,
    "devices": [
        {
            "nukiId": 0,
            "isDoorSensorEnabled": true,
            "isRingToOpenEnabled": false,
            "isContinuousModeEnabled": false,
            "isDoorbellEnabled": false,
            "isSingleAccessoryModeEnabled": false,
            "unlatchFromLockedToUnlocked": false,
            "unlatchFromUnlockedToUnlocked": false,
            "lockFromLockedToLocked": false,
            "unlatchLock": true,
            "unlatchLockPreventUnlatchIfLocked": true,
            "leaveOpen": false,
            "defaultLockName": "Lock",
            "defaultLatchName": "Latch"
        }
    ],
    "isApiEnabled": false,
    "apiPort": 40011,
    "apiToken": "<YOUR-TOKEN>"
}

Unfortunately I don't see any change in the Apple Home Kit.

Do I have to deactivate Home Kit in the Nuki app or does the plugin access it?

**Comment by redeemer666** [comment]
Hi Snub, on NukiID you have to put the ID of your Nuki. Instructions on how to retrieve are on the main page of the project.

**Comment by Snub2000** [comment]
okay, that was my mistake, now it works, thanks again.  I assumed the first device has ID 0, the next ID1, etc.
