### ISSUE TITLE
Lock automatic delete after error 503

### ISSUE THREAD

**Issue by Nastras** [lukasroegner/homebridge-nuki#9]
Hello Lukas,

i finished today for the first time through a scene when leaving both nukis simultaneously.

Error 503 occurred. I have set my Homebridge to automatically restart the instance when error 503 occurs.

At the same time the plugin deleted one of my locks after the restart.

The config was unchanged, in homekit the lock also disappeared.

After restarting the instance, the lock was added again by the plugin.

Do you have any idea where the problem is?

**Comment by Nastras** [comment]
Here the Log:

p 26 07:24:13 HBS homebridge[7245]: [NukiPlatform] Cached accessories loaded.
Sep 26 07:24:13 HBS homebridge[7245]: Homebridge is running on port 51814.
Sep 26 07:24:15 HBS homebridge[7245]: [NukiPlatform] Removing accessory with Nuki ID XXX and kind LockAccessory.
Sep 26 07:24:15 HBS homebridge[7245]: [NukiPlatform] Got devices from the Nuki Bridge API.
Sep 26 07:24:15 HBS homebridge[7245]: [NukiPlatform] Callback server started.
Sep 26 07:24:16 HBS homebridge[7245]: [NukiPlatform] Callback received.
Sep 26 07:24:18 HBS homebridge[7245]: [NukiPlatform] Callback already registered.
Sep 26 07:34:32 HBS systemd[1]: Stopping homebridge-nuki.service...
Sep 26 07:34:32 HBS homebridge[7245]: Got SIGTERM, shutting down Homebridge...
Sep 26 07:34:37 HBS systemd[1]: homebridge-nuki.service: Main process exited, code=exited, status=143/n/a
Sep 26 07:34:37 HBS systemd[1]: homebridge-nuki.service: Failed with result 'exit-code'.
Sep 26 07:34:37 HBS systemd[1]: Stopped homebridge-nuki.service.
Sep 26 07:34:37 HBS systemd[1]: Started homebridge-nuki.service.
Sep 26 07:34:38 HBS homebridge[16292]: Loaded config.json with 0 accessories and 1 platforms.
Sep 26 07:34:38 HBS homebridge[16292]: ---
Sep 26 07:34:39 HBS homebridge[16292]: Loaded plugin: homebridge-nuki
Sep 26 07:34:39 HBS homebridge[16292]: Registering platform 'homebridge-nuki.NukiPlatform'
Sep 26 07:34:39 HBS homebridge[16292]: ---
Sep 26 07:34:39 HBS homebridge[16292]: Loading 1 platforms...
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] Initializing NukiPlatform platform...
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] Homebridge API available.
Sep 26 07:34:39 HBS homebridge[16292]: Loading 0 accessories...
Sep 26 07:34:39 HBS homebridge[16292]: Setup Payload:
Sep 26 07:34:39 HBS homebridge[16292]: X-HM://
Sep 26 07:34:39 HBS homebridge[16292]: Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
Sep 26 07:34:39 HBS homebridge[16292]:                        
Sep 26 07:34:39 HBS homebridge[16292]:     ┌────────────┐     
Sep 26 07:34:39 HBS homebridge[16292]:     │            │     
Sep 26 07:34:39 HBS homebridge[16292]:     └────────────┘     
Sep 26 07:34:39 HBS homebridge[16292]:                        
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] Cached accessories loaded.
Sep 26 07:34:39 HBS homebridge[16292]: Homebridge is running on port 51814.
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] Device with Nuki ID XXX and name Türschloss 1 is a SmartLock.
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] Adding new accessory with Nuki ID XXX and kind LockAccessory.
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] XXX - Updating lock state: SECURED/SECURED
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] XXX - Updating critical battery: false
Sep 26 07:34:39 HBS homebridge[16292]: HAP Warning: Characteristic 00000079-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000045-0000-1000-8000-0026BB765291. Adding anyway.
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] Device with Nuki ID XXX and name Türschloss 2 is a SmartLock.
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] XXX - Updating lock state: SECURED/SECURED
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] XXX - Updating critical battery: false
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] Got devices from the Nuki Bridge API.
Sep 26 07:34:39 HBS homebridge[16292]: [NukiPlatform] Callback server started.
Sep 26 07:34:42 HBS homebridge[16292]: [NukiPlatform] Callback already registered.
Sep 26 0

**Comment by Nastras** [comment]
Addition: Up to now I have only controlled the locks separately which worked wonderfully.

It seems that when controlling both locks at the same time the nuki bridge can't handle the requests because of error 503.

Would it be possible to set a priority in the config which lock will be controlled first when controlling multiple locks at the same time and only when this is done will the second lock be controlled?

**Comment by lukasroegner** [comment]
> At the same time the plugin deleted one of my locks after the restart.
> The config was unchanged, in homekit the lock also disappeared.
> After restarting the instance, the lock was added again by the plugin.

It seems that the lock hasn't been included in the `/list` response of the Nuki Bridge, which is why the lock has been removed from HomeKit (when starting up, the plugin removes accessories that are no longer available).

> Error 503 occurred. I have set my Homebridge to automatically restart the instance when error 503 occurs.

Can you explain how/why you restart homebridge automatically when this error occurs?

**Comment by Nastras** [comment]
I have a script that monitors the journal and looks for the error. If it detects an error it makes a restart.

If I understood you correctly, the bridge crashed and didn't generate a temporary message saying which locks are known?

**Comment by lukasroegner** [comment]
I think it is not necessary to restart homebridge and the plugin. I've implemented
* A queue, which should prevent multiple simultaneous requests to the Bridge
* A retry mechanism that tries to execute the requested action if an error (like 503) occurs
* A timing mechanism, which ensures that there is enough time between two requests so that the Bridge does not throw errors

**Comment by Nastras** [comment]
I didn't know you'd put anything like that in before. I will turn off the script and try again to control both locks at the same time.

I'll get back to you right away.

**Comment by Nastras** [comment]
I have turned off the script and again 3 times on and closed both locks over a scene. So far it has worked very well.

But it has not yet encountered the error 503.

That a lock was deleted is probably due to the combination 503 and the restart of the instance?

I will watch it further and report the days again if it works.

Thanks for your help and time.

**Comment by lukasroegner** [comment]
Exactly, deletion seemed to happen as a result of restart and 503.

**Comment by Nastras** [comment]
I guess that wasn't a good idea of mine.

As I said, I report the days again how it runs.

Thank you!

**Comment by Nastras** [comment]
Good morning, I promised to get back to you with a feedback.
After a few days I have to say it is going really well. The bug was my script which rebooted homebridge-nuki.

Thanks again!
